Find the Closest Palindrome (Leetcode) Added problem number 564
CodeHarborHub/codeharborhub.github.io pull request #1021
Opened 2024-06-11 11:41 UTC by vivekvardhan2810

## Related Issue

Fixed : #1006 

## Description

I had Added the Solution of problem "Find the Closest Palindrome" under Leetcode Solution > 0500-0599 > 0564

## Type of PR

- [x] Feature enhancement
- [x] Documentation update

## Screenshots / Videos (if applicable)

[Attach any relevant screenshots or videos demonstrating the changes]

## Checklist
- [x] I have performed a self-review of my code.
- [x] I have read and followed the Contribution Guidelines.
- [x] I have tested the changes thoroughly before submitting this pull request.
- [x] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [x] I have commented my code, particularly in hard-to-understand areas.

## Additional Context

[Include any additional information or context that might be helpful for reviewers.]

## Resources for Guidance

Here are some resources that may be helpful as you contribute to CodeHarborHub:
- [Code Harbor Hub Community Features](https://www.codeharborhub.live/community/features)
- [Docusaurus Documentation](https://docusaurus.io/docs/create-doc)
- [React.js Documentation](https://legacy.reactjs.org/docs/getting-started.html)
- [Markdown Guide](https://www.markdownguide.org/)
- [MDX Documentation](https://mdxjs.com/docs/)
- [Mermaid Documentation](https://mermaid.js.org/)

**Resources for DSA Features on Our Site:**

- Tabs: [Switch Languages](https://www.codeharborhub.live/community/features#multi-language-support-code-blocks)
- [Line Numbering](https://www.codeharborhub.live/community/features#line-numbering)
- [Math Equations](https://www.codeharborhub.live/community/features#math-equations-with-katex)

2024-06-11 11:43 UTC, vivekvardhan2810 commented
Hi @Ajay-Dhangar , I have added solution you can review it.

And tell me the suggestions.

2024-06-12 07:28 UTC, Ajay-Dhangar requested changes
change your code based on suggestions

2024-06-12 07:28 UTC, Ajay-Dhangar commented on dsa-solutions/lc-solutions/0500-0599/0564- Find the Closest Palindrome.md
> +- $1 <= n.length <= 18$
replace `$1 <= n.length <= 18$` to `$1 \leq n.length \leq 18$`

2024-06-12 07:28 UTC, Ajay-Dhangar commented on dsa-solutions/lc-solutions/0500-0599/0564- Find the Closest Palindrome.md
> +- $n$ is representing an integer in the range [1, 10^18 - 1].
replace `10^18` to `$10^18$`

2024-06-12 07:36 UTC, vivekvardhan2810 commented
@Ajay-Dhangar resolved and done.

2024-06-12 09:11 UTC, merged