Create WebSockets.md
CodeHarborHub/codeharborhub.github.io pull request #1658
Opened 2024-06-19 14:21 UTC by AKSHITHA-CHILUKA

## Related Issue

[Cite any related issue(s) this pull request addresses. If none, simply state "None”]

## Description

[Please include a brief description of the changes or features added]

## Type of PR

- [ ] Bug fix
- [ ] Feature enhancement
- [ ] Documentation update
- [ ] Security enhancement
- [ ] Other (specify): _______________

## Screenshots / Videos (if applicable)

[Attach any relevant screenshots or videos demonstrating the changes]

## Checklist
- [ ] I have performed a self-review of my code.
- [ ] I have read and followed the Contribution Guidelines.
- [ ] I have tested the changes thoroughly before submitting this pull request.
- [ ] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have followed the code style guidelines of this project.
- [ ] I have checked for any existing open issues that my pull request may address.
- [ ] I have ensured that my changes do not break any existing functionality.
- [ ] Each contributor is allowed to create a maximum of 4 issues per day. This helps us manage and address issues efficiently.
- [ ] I have read the resources for guidance listed below.
- [ ] I have followed security best practices in my code changes.

## Additional Context

[Include any additional information or context that might be helpful for reviewers.]

## Resources for Guidance

Please read the following resources before submitting your contribution:

- [ ] [Code Harbor Hub Community Features](https://www.codeharborhub.live/community/features)
- [ ] [Docusaurus Documentation](https://docusaurus.io/docs/create-doc)
- [ ] [React.js Documentation](https://legacy.reactjs.org/docs/getting-started.html)
- [ ] [Markdown Guide](https://www.markdownguide.org/)
- [ ] [MDX Documentation](https://mdxjs.com/docs/)
- [ ] [Mermaid Documentation](https://mermaid.js.org/)

**Resources for DSA Features on Our Site:**

- [ ] [Tabs: Switch Languages](https://www.codeharborhub.live/community/features#multi-language-support-code-blocks)
- [ ] [Line Numbering](https://www.codeharborhub.live/community/features#line-numbering)
- [ ] [Math Equations](https://www.codeharborhub.live/community/features#math-equations-with-katex) 

## Contribution Guidelines

Thank you for considering contributing to our project! To ensure smooth collaboration and effective contribution management, please adhere to the following guidelines:

### Issue Creation

1. **Limit on Issues:**
   - Each contributor is allowed to create a maximum of **4 issues per day**. This helps us manage and address issues efficiently.

### Contribution Levels

2. **Basic Contributions:**
   - This project is primarily focused on documentation. Most of the setup has been completed, so contributors will generally need to work on basic code tasks, such as writing tests.
   - For these tasks, issues will be assigned the **level1** label.

3. **Acknowledging Hard Work:**
   - If a contributor puts in significant effort on a task, the issue will be upgraded to **level2**. This is our way of recognizing and appreciating extra effort.

4. **Feature Additions and Component Work:**
   - Contributors working on new features or components using JSX/TSX will be assigned a level based on the complexity and quality of their work.
   - The more complex and valuable the contribution, the higher the level assigned.

### Level Definitions

- **Level1:**
  - Tasks are straightforward, such as fixing minor bugs, writing tests, or making simple documentation updates.
- **Level2:**
  - Tasks require more effort, such as addressing complex bugs, improving existing features, or making substantial documentation improvements.
- **Level3:**
  - Tasks are highly complex and involve significant new feature development, major refactoring, or extensive contributions to the project’s core components.

We look forward to your contributions and appreciate your effort in helping us improve the project!

2024-06-19 15:28 UTC, AKSHITHA-CHILUKA commented
will the score be updated onto the leaderboard?

2024-06-19 16:46 UTC, Ajay-Dhangar requested changes
@AKSHITHA-CHILUKA Your code seems incomplete. Please provide the entire code and make sure it follows our guidelines.

2024-06-20 14:30 UTC, AKSHITHA-CHILUKA reviewed
completed the pending code

2024-06-20 14:32 UTC, AKSHITHA-CHILUKA commented
Also sir can you update my score in the leaderboard

2024-06-21 02:29 UTC, Ajay-Dhangar requested changes
update code based on suggestions

2024-06-21 02:29 UTC, Ajay-Dhangar commented on docs/WebSockets.md
> +
replace 

```md
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>WebSocket Client</title>
  <script>
    const ws = new WebSocket('ws://localhost:8080');

    // WebSocket open event
    ws.addEventListener('open', () => {
      console.log('Connected to WebSocket server');
    });

    // WebSocket message event
    ws.addEventListener('message', (event) => {
      console.log(`Received message from server: ${event.data}`);
    });

    // WebSocket close event
    ws.addEventListener('close', () => {
      console.log('Disconnected from WebSocket server');
    });

    // Function to send a message to the WebSocket server
    function sendMessage() {
      const message = document.getElementById('message').value;
      ws.send(message);
    }
  </script>
</head>
<body>
  <h1>WebSocket Client</h1>
  <input type="text" id="message" placeholder="Enter message">
  <button onclick="sendMessage()">Send</button>
</body>
</html>
```

to


````md
```html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>WebSocket Client</title>
  <script>
    const ws = new WebSocket('ws://localhost:8080');

    // WebSocket open event
    ws.addEventListener('open', () => {
      console.log('Connected to WebSocket server');
    });

    // WebSocket message event
    ws.addEventListener('message', (event) => {
      console.log(`Received message from server: ${event.data}`);
    });

    // WebSocket close event
    ws.addEventListener('close', () => {
      console.log('Disconnected from WebSocket server');
    });

    // Function to send a message to the WebSocket server
    function sendMessage() {
      const message = document.getElementById('message').value;
      ws.send(message);
    }
  </script>
</head>
<body>
  <h1>WebSocket Client</h1>
  <input type="text" id="message" placeholder="Enter message">
  <button onclick="sendMessage()">Send</button>
</body>
</html>
```
````

2024-06-21 02:29 UTC, Ajay-Dhangar commented on docs/WebSockets.md
> +
add <code>```</code>

2024-06-21 02:32 UTC, Ajay-Dhangar commented
> Also sir can you update my score in the leaderboard

I don't do this but your score is update based on your work like if your PRs successful merge then calculate your levels and added your score in leaderboard  So, don't worry.

2024-06-22 08:49 UTC, Ajay-Dhangar approved these changes
Done

2024-06-22 08:56 UTC, merged