Adedd a Page Scroll Progress Bar at the Top of Your Startup Webpage
CodeHarborHub/codeharborhub.github.io pull request #2365
Opened 2024-06-30 13:29 UTC by TheNikhilRaj

## Related Issue

Adedd a Page Scroll Progress Bar at the Top of Your Startup Webpage

## Type of PR
#2183

- [ ] Bug fix
- [ ] Feature enhancement
- [ ] Documentation update
- [ ] Security enhancement
- [ ] Other (specify): _______________

## Screenshots / Videos (if applicable)

![Capture](https://github.com/CodeHarborHub/codeharborhub.github.io/assets/129590267/0606ce2c-95e7-40cf-9449-c1fa32993187)

## Checklist
- [ ] I have performed a self-review of my code.
- [ ] I have read and followed the Contribution Guidelines.
- [ ] I have tested the changes thoroughly before submitting this pull request.
- [ ] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have followed the code style guidelines of this project.
- [ ] I have checked for any existing open issues that my pull request may address.
- [ ] I have ensured that my changes do not break any existing functionality.
- [ ] Each contributor is allowed to create a maximum of 4 issues per day. This helps us manage and address issues efficiently.
- [ ] I have read the resources for guidance listed below.
- [ ] I have followed security best practices in my code changes.

## Additional Context

[Include any additional information or context that might be helpful for reviewers.]

## Resources for Guidance

Please read the following resources before submitting your contribution:

- [ ] [Code Harbor Hub Community Features](https://www.codeharborhub.live/community/features)
- [ ] [Docusaurus Documentation](https://docusaurus.io/docs/create-doc)
- [ ] [React.js Documentation](https://legacy.reactjs.org/docs/getting-started.html)
- [ ] [Markdown Guide](https://www.markdownguide.org/)
- [ ] [MDX Documentation](https://mdxjs.com/docs/)
- [ ] [Mermaid Documentation](https://mermaid.js.org/)

**Resources for DSA Features on Our Site:**

- [ ] [Tabs: Switch Languages](https://www.codeharborhub.live/community/features#multi-language-support-code-blocks)
- [ ] [Line Numbering](https://www.codeharborhub.live/community/features#line-numbering)
- [ ] [Math Equations](https://www.codeharborhub.live/community/features#math-equations-with-katex) 

## Contribution Guidelines

Thank you for considering contributing to our project! To ensure smooth collaboration and effective contribution management, please adhere to the following guidelines:

### Issue Creation

1. **Limit on Issues:**
   - Each contributor is allowed to create a maximum of **4 issues per day**. This helps us manage and address issues efficiently.

### Contribution Levels

2. **Basic Contributions:**
   - This project is primarily focused on documentation. Most of the setup has been completed, so contributors will generally need to work on basic code tasks, such as writing tests.
   - For these tasks, issues will be assigned the **level1** label.

3. **Acknowledging Hard Work:**
   - If a contributor puts in significant effort on a task, the issue will be upgraded to **level2**. This is our way of recognizing and appreciating extra effort.

4. **Feature Additions and Component Work:**
   - Contributors working on new features or components using JSX/TSX will be assigned a level based on the complexity and quality of their work.
   - The more complex and valuable the contribution, the higher the level assigned.

### Level Definitions

- **Level1:**
  - Tasks are straightforward, such as fixing minor bugs, writing tests, or making simple documentation updates.
- **Level2:**
  - Tasks require more effort, such as addressing complex bugs, improving existing features, or making substantial documentation improvements.
- **Level3:**
  - Tasks are highly complex and involve significant new feature development, major refactoring, or extensive contributions to the project’s core components.

We look forward to your contributions and appreciate your effort in helping us improve the project!

2024-06-30 15:53 UTC, Ajay-Dhangar requested changes
update code based on suggestions

2024-06-30 15:53 UTC, Ajay-Dhangar commented on src/components/HomePage/Header.tsx
> +      color: '#ff8800'
replace `color: '#ff8800'` to `color: 'var(--ifm-color-primary)'`

2024-06-30 15:53 UTC, Ajay-Dhangar commented on src/components/HomePage/Header.tsx
> +  color: '#ff8800'
replace `color: '#ff8800'` to `color: 'var(--ifm-color-primary)'`

2024-06-30 16:11 UTC, TheNikhilRaj commented
@Ajay-Dhangar  done update code based on suggestions!!

2024-07-01 03:47 UTC, Ajay-Dhangar commented
@TheNikhilRaj Can you solve errors

```bash
#12 4.542 npm warn deprecated workbox-google-analytics@7.0.0: It is not compatible with newer versions of GA starting with v4, as long as you are using GAv3 it should be ok, but the package is not longer being maintained
#12 6.187 npm warn deprecated figgy-pudding@3.5.2: This module is no longer supported.
#12 7.315 npm warn deprecated emailjs-com@3.2.0: The SDK name changed to @emailjs/browser
#12 9.412 npm warn deprecated chokidar@2.1.8: Chokidar 2 does not receive security updates since 2019. Upgrade to chokidar 3 with 15x fewer dependencies
#12 10.77 npm warn deprecated acorn-dynamic-import@4.0.0: This is probably built in to whatever tool you're using. If you still need it... idk
#12 17.22 
#12 17.22 added 1[97](https://github.com/CodeHarborHub/codeharborhub.github.io/actions/runs/9733300108/job/26860114973?pr=2365#step:3:98)8 packages, and audited 1979 packages in 17s
#12 17.22 
#12 17.22 401 packages are looking for funding
#12 17.22   run `npm fund` for details
#12 17.24 
#12 17.24 9 high severity vulnerabilities
#12 17.24 
#12 17.24 To address all issues, run:
#12 17.24   npm audit fix
#12 17.24 
#12 17.24 Run `npm audit` for details.
#12 DONE 18.8s

#13 [builder 5/6] COPY . .
#13 DONE 0.7s

#14 [builder 6/6] RUN npm run build
#14 0.307 
#14 0.307 > code-harbor-hub@0.0.0 build
#14 0.307 > docusaurus build
#14 0.307 
#14 1.442 (node:17) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
#14 1.442 (Use `node --trace-deprecation ...` to show where the warning was created)
#14 3.214 [INFO] [en] Creating an optimized production build...
#14 3.424 (node:17) Warning: To load an ES module, set "type": "module" in the package.json or use the .mjs extension.
#14 3.956 [WARNING] Sorry, the last update options require Git.
#14 5.0[98](https://github.com/CodeHarborHub/codeharborhub.github.io/actions/runs/9733300108/job/26860114973?pr=2365#step:3:99) [WARNING] Duplicate routes found!
#14 5.098 - Attempting to create page at /dsa-solutions/lc-solutions/0400-0499/sort-characters-by-frequency, but a page already exists at this route.
#14 5.098 - Attempting to create page at /dsa-solutions/lc-solutions/3100-31[99](https://github.com/CodeHarborHub/codeharborhub.github.io/actions/runs/9733300108/job/26860114973?pr=2365#step:3:100)/score-of-a-string, but a page already exists at this route.
#14 5.098 This could lead to non-deterministic routing behavior.
#14 6.186 ℹ Compiling Client
#14 6.210 ℹ Compiling Server
#14 41.90 LaTeX-incompatible input and strict mode is set to 'warn': Unrecognized Unicode character "⁡" (8289) [unknownSymbol]
#14 41.90 No character metrics for '⁡' in style 'Main-Regular' and mode 'text'
#14 41.90 LaTeX-incompatible input and strict mode is set to 'warn': Unrecognized Unicode character "⁡" (8289) [unknownSymbol]
#14 41.90 No character metrics for '⁡' in style 'Main-Regular' and mode 'text'
#14 41.90 LaTeX-incompatible input and strict mode is set to 'warn': Unrecognized Unicode character "⁡" (8289) [unknownSymbol]
#14 41.90 No character metrics for '⁡' in style 'Main-Regular' and mode 'text'
#14 41.90 LaTeX-incompatible input and strict mode is set to 'warn': Unrecognized Unicode character "⁡" (8289) [unknownSymbol]
#14 41.90 No character metrics for '⁡' in style 'Main-Regular' and mode 'text'
#14 41.90 LaTeX-incompatible input and strict mode is set to 'warn': Unrecognized Unicode character "⁡" (8289) [unknownSymbol]
#14 41.90 LaTeX-incompatible input and strict mode is set to 'warn': Unrecognized Unicode character "⁡" (8289) [unknownSymbol]
#14 41.90 No character metrics for '⁡' in style 'Main-Regular' and mode 'text'
#14 41.90 No character metrics for '⁡' in style 'Main-Regular' and mode 'text'
#14 41.90 LaTeX-incompatible input and strict mode is set to 'warn': Unrecognized Unicode character "⁡" (8289) [unknownSymbol]
#14 41.90 No character metrics for '⁡' in style 'Main-Regular' and mode 'text'
#14 41.95 LaTeX-incompatible input and strict mode is set to 'warn': Unrecognized Unicode character "⁡" (8289) [unknownSymbol]
#14 41.95 No character metrics for '⁡' in style 'Main-Regular' and mode 'text'
#14 41.95 LaTeX-incompatible input and strict mode is set to 'warn': Unrecognized Unicode character "⁡" (8289) [unknownSymbol]
#14 41.95 No character metrics for '⁡' in style 'Main-Regular' and mode 'text'
#14 41.95 LaTeX-incompatible input and strict mode is set to 'warn': Unrecognized Unicode character "⁡" (8289) [unknownSymbol]
#14 41.95 No character metrics for '⁡' in style 'Main-Regular' and mode 'text'
#14 42.05 LaTeX-incompatible input and strict mode is set to 'warn': Unrecognized Unicode character "⁡" (8289) [unknownSymbol]
#14 42.05 No character metrics for '⁡' in style 'Main-Regular' and mode 'text'
#14 42.05 LaTeX-incompatible input and strict mode is set to 'warn': Unrecognized Unicode character "⁡" (8289) [unknownSymbol]
#14 42.05 No character metrics for '⁡' in style 'Main-Regular' and mode 'text'
#14 42.05 LaTeX-incompatible input and strict mode is set to 'warn': Unrecognized Unicode character "⁡" (8289) [unknownSymbol]
#14 42.05 No character metrics for '⁡' in style 'Main-Regular' and mode 'text'
#14 42.06 LaTeX-incompatible input and strict mode is set to 'warn': Unrecognized Unicode character "⁡" (8289) [unknownSymbol]
#14 42.06 No character metrics for '⁡' in style 'Main-Regular' and mode 'text'
#14 42.06 LaTeX-incompatible input and strict mode is set to 'warn': Unrecognized Unicode character "⁡" (8289) [unknownSymbol]
#14 42.06 LaTeX-incompatible input and strict mode is set to 'warn': Unrecognized Unicode character "⁡" (8289) [unknownSymbol]
#14 42.06 No character metrics for '⁡' in style 'Main-Regular' and mode 'text'
#14 42.06 No character metrics for '⁡' in style 'Main-Regular' and mode 'text'
#14 42.06 LaTeX-incompatible input and strict mode is set to 'warn': Unrecognized Unicode character "⁡" (8289) [unknownSymbol]
#14 42.06 No character metrics for '⁡' in style 'Main-Regular' and mode 'text'
#14 42.11 LaTeX-incompatible input and strict mode is set to 'warn': Unrecognized Unicode character "⁡" (8289) [unknownSymbol]
#14 42.11 No character metrics for '⁡' in style 'Main-Regular' and mode 'text'
#14 42.11 LaTeX-incompatible input and strict mode is set to 'warn': Unrecognized Unicode character "⁡" (8289) [unknownSymbol]
#14 42.11 No character metrics for '⁡' in style 'Main-Regular' and mode 'text'
#14 42.11 LaTeX-incompatible input and strict mode is set to 'warn': Unrecognized Unicode character "⁡" (8289) [unknownSymbol]
#14 42.11 No character metrics for '⁡' in style 'Main-Regular' and mode 'text'
#14 48.51 LaTeX-incompatible input and strict mode is set to 'warn': Unrecognized Unicode character "​" (8203) [unknownSymbol]
#14 48.51 No character metrics for '​' in style 'Main-Regular' and mode 'text'
#14 48.86 LaTeX-incompatible input and strict mode is set to 'warn': Unrecognized Unicode character "​" (8203) [unknownSymbol]
#14 48.86 No character metrics for '​' in style 'Main-Regular' and mode 'text'
#14 51.52 LaTeX-incompatible input and strict mode is set to 'warn': Unrecognized Unicode character "⁡" (8289) [unknownSymbol]
#14 51.52 No character metrics for '⁡' in style 'Main-Regular' and mode 'text'
#14 51.57 LaTeX-incompatible input and strict mode is set to 'warn': Unrecognized Unicode character "⁡" (8289) [unknownSymbol]
#14 51.57 No character metrics for '⁡' in style 'Main-Regular' and mode 'text'
#14 65.41 LaTeX-incompatible input and strict mode is set to 'warn': Unrecognized Unicode character "⁡" (8289) [unknownSymbol]
#14 65.41 LaTeX-incompatible input and strict mode is set to 'warn': Unrecognized Unicode character "⁡" (8289) [unknownSymbol]
#14 65.41 No character metrics for '⁡' in style 'Main-Regular' and mode 'text'
#14 65.41 No character metrics for '⁡' in style 'Main-Regular' and mode 'text'
#14 65.47 LaTeX-incompatible input and strict mode is set to 'warn': Unrecognized Unicode characte [...]

2024-07-01 04:16 UTC, TheNikhilRaj commented
> @TheNikhilRaj Can you solve errors
> 
> ```bash
> #12 4.542 npm warn deprecated workbox-google-analytics@7.0.0: It is not compatible with newer versions of GA starting with v4, as long as you are using GAv3 it should be ok, but the package is not longer being maintained
> #12 6.187 npm warn deprecated figgy-pudding@3.5.2: This module is no longer supported.
> #12 7.315 npm warn deprecated emailjs-com@3.2.0: The SDK name changed to @emailjs/browser
> #12 9.412 npm warn deprecated chokidar@2.1.8: Chokidar 2 does not receive security updates since 2019. Upgrade to chokidar 3 with 15x fewer dependencies
> #12 10.77 npm warn deprecated acorn-dynamic-import@4.0.0: This is probably built in to whatever tool you're using. If you still need it... idk
> #12 17.22 
> #12 17.22 added 1[97](https://github.com/CodeHarborHub/codeharborhub.github.io/actions/runs/9733300108/job/26860114973?pr=2365#step:3:98)8 packages, and audited 1979 packages in 17s
> #12 17.22 
> #12 17.22 401 packages are looking for funding
> #12 17.22   run `npm fund` for details
> #12 17.24 
> #12 17.24 9 high severity vulnerabilities
> #12 17.24 
> #12 17.24 To address all issues, run:
> #12 17.24   npm audit fix
> #12 17.24 
> #12 17.24 Run `npm audit` for details.
> #12 DONE 18.8s
> 
> #13 [builder 5/6] COPY . .
> #13 DONE 0.7s
> 
> #14 [builder 6/6] RUN npm run build
> #14 0.307 
> #14 0.307 > code-harbor-hub@0.0.0 build
> #14 0.307 > docusaurus build
> #14 0.307 
> #14 1.442 (node:17) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
> #14 1.442 (Use `node --trace-deprecation ...` to show where the warning was created)
> #14 3.214 [INFO] [en] Creating an optimized production build...
> #14 3.424 (node:17) Warning: To load an ES module, set "type": "module" in the package.json or use the .mjs extension.
> #14 3.956 [WARNING] Sorry, the last update options require Git.
> #14 5.0[98](https://github.com/CodeHarborHub/codeharborhub.github.io/actions/runs/9733300108/job/26860114973?pr=2365#step:3:99) [WARNING] Duplicate routes found!
> #14 5.098 - Attempting to create page at /dsa-solutions/lc-solutions/0400-0499/sort-characters-by-frequency, but a page already exists at this route.
> #14 5.098 - Attempting to create page at /dsa-solutions/lc-solutions/3100-31[99](https://github.com/CodeHarborHub/codeharborhub.github.io/actions/runs/9733300108/job/26860114973?pr=2365#step:3:100)/score-of-a-string, but a page already exists at this route.
> #14 5.098 This could lead to non-deterministic routing behavior.
> #14 6.186 ℹ Compiling Client
> #14 6.210 ℹ Compiling Server
> #14 41.90 LaTeX-incompatible input and strict mode is set to 'warn': Unrecognized Unicode character "⁡" (8289) [unknownSymbol]
> #14 41.90 No character metrics for '⁡' in style 'Main-Regular' and mode 'text'
> #14 41.90 LaTeX-incompatible input and strict mode is set to 'warn': Unrecognized Unicode character "⁡" (8289) [unknownSymbol]
> #14 41.90 No character metrics for '⁡' in style 'Main-Regular' and mode 'text'
> #14 41.90 LaTeX-incompatible input and strict mode is set to 'warn': Unrecognized Unicode character "⁡" (8289) [unknownSymbol]
> #14 41.90 No character metrics for '⁡' in style 'Main-Regular' and mode 'text'
> #14 41.90 LaTeX-incompatible input and strict mode is set to 'warn': Unrecognized Unicode character "⁡" (8289) [unknownSymbol]
> #14 41.90 No character metrics for '⁡' in style 'Main-Regular' and mode 'text'
> #14 41.90 LaTeX-incompatible input and strict mode is set to 'warn': Unrecognized Unicode character "⁡" (8289) [unknownSymbol]
> #14 41.90 LaTeX-incompatible input and strict mode is set to 'warn': Unrecognized Unicode character "⁡" (8289) [unknownSymbol]
> #14 41.90 No character metrics for '⁡' in style 'Main-Regular' and mode 'text'
> #14 41.90 No character metrics for '⁡' in style 'Main-Regular' and mode 'text'
> #14 41.90 LaTeX-incompatible input and strict mode is set to 'warn': Unrecognized Unicode character "⁡" (8289) [unknownSymbol]
> #14 41.90 No character metrics for '⁡' in style 'Main-Regular' and mode 'text'
> #14 41.95 LaTeX-incompatible input and strict mode is set to 'warn': Unrecognized Unicode character "⁡" (8289) [unknownSymbol]
> #14 41.95 No character metrics for '⁡' in style 'Main-Regular' and mode 'text'
> #14 41.95 LaTeX-incompatible input and strict mode is set to 'warn': Unrecognized Unicode character "⁡" (8289) [unknownSymbol]
> #14 41.95 No character metrics for '⁡' in style 'Main-Regular' and mode 'text'
> #14 41.95 LaTeX-incompatible input and strict mode is set to 'warn': Unrecognized Unicode character "⁡" (8289) [unknownSymbol]
> #14 41.95 No character metrics for '⁡' in style 'Main-Regular' and mode 'text'
> #14 42.05 LaTeX-incompatible input and strict mode is set to 'warn': Unrecognized Unicode character "⁡" (8289) [unknownSymbol]
> #14 42.05 No character metrics for '⁡' in style 'Main-Regular' and mode 'text'
> #14 42.05 LaTeX-incompatible input and strict mode is set to 'warn': Unrecognized Unicode character "⁡" (8289) [unknownSymbol]
> #14 42.05 No character metrics for '⁡' in style 'Main-Regular' and mode 'text'
> #14 42.05 LaTeX-incompatible input and strict mode is set to 'warn': Unrecognized Unicode character "⁡" (8289) [unknownSymbol]
> #14 42.05 No character metrics for '⁡' in style 'Main-Regular' and mode 'text'
> #14 42.06 LaTeX-incompatible input and strict mode is set to 'warn': Unrecognized Unicode character "⁡" (8289) [unknownSymbol]
> #14 42.06 No character metrics for '⁡' in style 'Main-Regular' and mode 'text'
> #14 42.06 LaTeX-incompatible input and strict mode is set to 'warn': Unrecognized Unicode character "⁡" (8289) [unknownSymbol]
> #14 42.06 LaTeX-incompatible input and strict mode is set to 'warn': Unrecognized Unicode character "⁡" (8289) [unknownSymbol]
> #14 42.06 No character metrics for '⁡' in style 'Main-Regular' and mode 'text'
> #14 42.06 No character metrics for '⁡' in style 'Main-Regular' and mode 'text'
> #14 42.06 LaTeX-incompatible input and strict mode is set to 'warn': Unrecognized Unicode character "⁡" (8289) [unknownSymbol]
> #14 42.06 No character metrics for '⁡' in style 'Main-Regular' and mode 'text'
> #14 42.11 LaTeX-incompatible input and strict mode is set to 'warn': Unrecognized Unicode character "⁡" (8289) [unknownSymbol]
> #14 42.11 No character metrics for '⁡' in style 'Main-Regular' and mode 'text'
> #14 42.11 LaTeX-incompatible input and strict mode is set to 'warn': Unrecognized Unicode character "⁡" (8289) [unknownSymbol]
> #14 42.11 No character metrics for '⁡' in style 'Main-Regular' and mode 'text'
> #14 42.11 LaTeX-incompatible input and strict mode is set to 'warn': Unrecognized Unicode character "⁡" (8289) [unknownSymbol]
> #14 42.11 No character metrics for '⁡' in style 'Main-Regular' and mode 'text'
> #14 48.51 LaTeX-incompatible input and strict mode is set to 'warn': Unrecognized Unicode character "​" (8203) [unknownSymbol]
> #14 48.51 No character metrics for '​' in style 'Main-Regular' and mode 'text'
> #14 48.86 LaTeX-incompatible input and strict mode is set to 'warn': Unrecognized Unicode character "​" (8203) [unknownSymbol]
> #14 48.86 No character metrics for '​' in style 'Main-Regular' and mode 'text'
> #14 51.52 LaTeX-incompatible input and strict mode is set to 'warn': Unrecognized Unicode character "⁡" (8289) [unknownSymbol]
> #14 51.52 No character metrics for '⁡' in style 'Main-Regular' and mode 'text'
> #14 51.57 LaTeX-incompatible input and strict mode is set to 'warn': Unrecognized Unicode character "⁡" (8289) [unknownSymbol]
> #14 51.57 No character metrics for '⁡' in style 'Main-Regular' and mode 'text'
> #14 65.41 LaTeX-incompatible input and strict mode is set to 'warn': Unrecognized Unicode character "⁡" (8289) [unknownSymbol]
> #14 65.41 LaTeX-incompatible input and strict mode is set to 'warn': Unrecognized Unicode character "⁡" (8289) [unknownSymbol]
> #14 65.41 No character metrics for '⁡' in style 'Main-Regular' and mode  [...]

2024-07-01 06:41 UTC, TheNikhilRaj commented
@Ajay-Dhangar  when points update on leaderboard under Gssoc'24??

2024-07-01 08:45 UTC, Ajay-Dhangar commented
@TheNikhilRaj okay. waiting for some time I need to debug code and provide you some suggestions.

2024-07-01 09:04 UTC, Ajay-Dhangar requested changes
You need to import and export of `ScrollProgress` and used Best practice approach for `jsx`.

**This page is using the production build of React. ✅**

2024-07-01 09:16 UTC, TheNikhilRaj commented
> You need to import and export of `ScrollProgress` and used Best practice approach for `jsx`.
> 
> **This page is using the production build of React. ✅**

what import and export?

2024-07-01 12:51 UTC, Ajay-Dhangar commented
@TheNikhilRaj because you created two different components and I see you used other components code without import So, you can define or may be used both components code in one component I will manage to my side.

2024-07-05 03:42 UTC, Ajay-Dhangar reviewed
Debug code for solving errors

2024-07-05 03:51 UTC, merged

2024-07-05 03:51 UTC, Ajay-Dhangar reviewed
Done