added rateus feature in home page
CodeHarborHub/codeharborhub.github.io pull request #2409
Opened 2024-07-01 14:33 UTC by MuraliDharan7

## Related Issue
- Closes #2255 

## Description

Added Rateus feature where users can rate the page out of 5, also can give feedback about the same.

## Type of PR

- [X ] Feature enhancement

## Screenshots / Videos (if applicable)

https://github.com/CodeHarborHub/codeharborhub.github.io/assets/130668745/f65d783e-7423-4a6c-a174-0a3a305f86d5

## Checklist
- [X ] I have performed a self-review of my code.
- [X ] I have read and followed the Contribution Guidelines.
- [X ] I have tested the changes thoroughly before submitting this pull request.
- [X ] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [X ] I have commented my code, particularly in hard-to-understand areas.
- [X ] I have followed the code style guidelines of this project.
- [X ] I have checked for any existing open issues that my pull request may address.
- [ ] I have ensured that my changes do not break any existing functionality.
- [X ] Each contributor is allowed to create a maximum of 4 issues per day. This helps us manage and address issues efficiently.
- [X ] I have read the resources for guidance listed below.
- [ X] I have followed security best practices in my code changes.

2024-07-01 14:39 UTC, MuraliDharan7 commented
@Ajay-Dhangar Can you guide through the errors, it would be helpful for me to solve the error as fast.

2024-07-01 15:14 UTC, Ajay-Dhangar requested changes
update your code based on suggestions

2024-07-01 15:14 UTC, Ajay-Dhangar commented on src/components/RateUsPopup/RateUsPopup.module.css
> +  textarea {
replace `textarea` to `.popupOverlay form textarea` for good practice

2024-07-01 15:14 UTC, Ajay-Dhangar commented on src/components/Tweet/index.tsx
> +import React, {useState, type ReactNode} from 'react';
`useState` is define but not use it. If not using then remove for good practice

2024-07-01 17:43 UTC, MuraliDharan7 commented
Could you please check the changes?

2024-07-02 00:38 UTC, Ajay-Dhangar approved these changes
Done

2024-07-02 00:38 UTC, merged