Added Cycle sort
CodeHarborHub/codeharborhub.github.io pull request #2869
Opened 2024-07-10 09:48 UTC by pavitraag

## Related Issue
Added cycle sort

## Type of PR

- [ ] Bug fix
- [X] Feature enhancement
- [ ] Documentation update
- [ ] Security enhancement
- [ ] Other (specify): _______________

## Checklist
- [X] I have performed a self-review of my code.
- [X] I have read and followed the Contribution Guidelines.
- [X] I have tested the changes thoroughly before submitting this pull request.
- [X] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [] I have commented my code, particularly in hard-to-understand areas.
- [X] I have followed the code style guidelines of this project.
- [X] I have checked for any existing open issues that my pull request may address.
- [X] I have ensured that my changes do not break any existing functionality.
- [X] Each contributor is allowed to create a maximum of 4 issues per day. This helps us manage and address issues efficiently.
- [X] I have read the resources for guidance listed below.
- [X] I have followed security best practices in my code changes.

## Contribution Guidelines

Thank you for considering contributing to our project! To ensure smooth collaboration and effective contribution management, please adhere to the following guidelines:

### Issue Creation

1. **Limit on Issues:**
   - Each contributor is allowed to create a maximum of **4 issues per day**. This helps us manage and address issues efficiently.

### Contribution Levels

2. **Basic Contributions:**
   - This project is primarily focused on documentation. Most of the setup has been completed, so contributors will generally need to work on basic code tasks, such as writing tests.
   - For these tasks, issues will be assigned the **level1** label.

3. **Acknowledging Hard Work:**
   - If a contributor puts in significant effort on a task, the issue will be upgraded to **level2**. This is our way of recognizing and appreciating extra effort.

4. **Feature Additions and Component Work:**
   - Contributors working on new features or components using JSX/TSX will be assigned a level based on the complexity and quality of their work.
   - The more complex and valuable the contribution, the higher the level assigned.

### Level Definitions

- **Level1:**
  - Tasks are straightforward, such as fixing minor bugs, writing tests, or making simple documentation updates.
- **Level2:**
  - Tasks require more effort, such as addressing complex bugs, improving existing features, or making substantial documentation improvements.
- **Level3:**
  - Tasks are highly complex and involve significant new feature development, major refactoring, or extensive contributions to the project’s core components.

We look forward to your contributions and appreciate your effort in helping us improve the project!

2024-07-10 09:52 UTC, pavitraag commented
Closes #2845

2024-07-10 10:50 UTC, Ajay-Dhangar requested changes
update your code based on suggestions

2024-07-10 10:50 UTC, Ajay-Dhangar commented on dsa-solutions/CycleSort.md
> +---
Please add some content to this file or delete it if it's not needed. We do not require empty files.

2024-07-10 10:50 UTC, Ajay-Dhangar commented on dsa-solutions/Sorting-Algorithms/Cycle-Sort.md
> +  - Time Complexity: O(n^2) in the worst case.
replace `O(n^2)` to `$O(n^2)$`

2024-07-10 10:50 UTC, Ajay-Dhangar commented on dsa-solutions/Sorting-Algorithms/Cycle-Sort.md
> +  - Space Complexity: O(1) additional space, as it sorts in-place.
replace `O(1)` to `$O(1)$`

2024-07-10 10:50 UTC, Ajay-Dhangar commented on dsa-solutions/Sorting-Algorithms/Cycle-Sort.md
> +- **Quadratic Time Complexity:** Has O(n^2) time complexity in the worst-case scenario, limiting efficiency for large datasets.
replace `O(n^2)` to `$O(n^2)$`

2024-07-11 04:40 UTC, pavitraag commented
@Ajay-Dhangar Resolved the issues

2024-07-11 08:15 UTC, Ajay-Dhangar approved these changes
Done

2024-07-11 08:15 UTC, merged