Added leetcode solution for Problem number 1305
CodeHarborHub/codeharborhub.github.io pull request #2896
Opened 2024-07-10 17:02 UTC by UtkarshBirla28

## Related Issue
Issue number ; #2779 

[Cite any related issue(s) this pull request addresses. If none, simply state "None”]

## Description

[Please include a brief description of the changes or features added]

## Type of PR

- [ ] Bug fix
- [ ] Feature enhancement
- [ ] Documentation update
- [ ] Security enhancement
- [ ] Other (specify): _______________

## Screenshots / Videos (if applicable)

[Attach any relevant screenshots or videos demonstrating the changes]

## Checklist
- [ ] I have performed a self-review of my code.
- [ ] I have read and followed the Contribution Guidelines.
- [ ] I have tested the changes thoroughly before submitting this pull request.
- [ ] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have followed the code style guidelines of this project.
- [ ] I have checked for any existing open issues that my pull request may address.
- [ ] I have ensured that my changes do not break any existing functionality.
- [ ] Each contributor is allowed to create a maximum of 4 issues per day. This helps us manage and address issues efficiently.
- [ ] I have read the resources for guidance listed below.
- [ ] I have followed security best practices in my code changes.

## Additional Context

[Include any additional information or context that might be helpful for reviewers.]

## Resources for Guidance

Please read the following resources before submitting your contribution:

- [ ] [Code Harbor Hub Community Features](https://www.codeharborhub.live/community/features)
- [ ] [Docusaurus Documentation](https://docusaurus.io/docs/create-doc)
- [ ] [React.js Documentation](https://legacy.reactjs.org/docs/getting-started.html)
- [ ] [Markdown Guide](https://www.markdownguide.org/)
- [ ] [MDX Documentation](https://mdxjs.com/docs/)
- [ ] [Mermaid Documentation](https://mermaid.js.org/)

**Resources for DSA Features on Our Site:**

- [ ] [Tabs: Switch Languages](https://www.codeharborhub.live/community/features#multi-language-support-code-blocks)
- [ ] [Line Numbering](https://www.codeharborhub.live/community/features#line-numbering)
- [ ] [Math Equations](https://www.codeharborhub.live/community/features#math-equations-with-katex) 

## Contribution Guidelines

Thank you for considering contributing to our project! To ensure smooth collaboration and effective contribution management, please adhere to the following guidelines:

### Issue Creation

1. **Limit on Issues:**
   - Each contributor is allowed to create a maximum of **4 issues per day**. This helps us manage and address issues efficiently.

### Contribution Levels

2. **Basic Contributions:**
   - This project is primarily focused on documentation. Most of the setup has been completed, so contributors will generally need to work on basic code tasks, such as writing tests.
   - For these tasks, issues will be assigned the **level1** label.

3. **Acknowledging Hard Work:**
   - If a contributor puts in significant effort on a task, the issue will be upgraded to **level2**. This is our way of recognizing and appreciating extra effort.

4. **Feature Additions and Component Work:**
   - Contributors working on new features or components using JSX/TSX will be assigned a level based on the complexity and quality of their work.
   - The more complex and valuable the contribution, the higher the level assigned.

### Level Definitions

- **Level1:**
  - Tasks are straightforward, such as fixing minor bugs, writing tests, or making simple documentation updates.
- **Level2:**
  - Tasks require more effort, such as addressing complex bugs, improving existing features, or making substantial documentation improvements.
- **Level3:**
  - Tasks are highly complex and involve significant new feature development, major refactoring, or extensive contributions to the project’s core components.

We look forward to your contributions and appreciate your effort in helping us improve the project!

2024-07-10 18:00 UTC, UtkarshBirla28 commented
@sanjay-kv Sir i have solved 2 issuees in this PR both of level 1 so please give me 20 pointd for that :)

2024-07-11 00:56 UTC, sanjay-kv commented
@UtkarshBirla28 anyhow this repo has limitation of 150 points giving 20 will reduce the no of PR you can issue. 
anyhow admin has to decide on this.

2024-07-11 07:51 UTC, Ajay-Dhangar requested changes
update code based on suggestions

2024-07-11 07:51 UTC, Ajay-Dhangar commented on dsa-problems/leetcode-problems/1300-1399.md
> +    "solutionLink":  "/dsa-solutions/lc-solutions/1300-1399/1305-All- Elements- in- Two- Binary -Search -Trees"
wrong url

2024-07-11 07:51 UTC, Ajay-Dhangar commented on dsa-solutions/lc-solutions/1300-1399/1305- All- Elements- in- Two- Binary -Search -Trees.md
> +id: All- Elements- in- Two- Binary -Search -Trees
replace `All- Elements- in- Two- Binary -Search -Trees` to `all-elements-in-two-binary-search-trees`

2024-07-11 07:51 UTC, Ajay-Dhangar commented on dsa-solutions/lc-solutions/1300-1399/1305- All- Elements- in- Two- Binary -Search -Trees.md
> +sidebar_label: 1305- All- Elements- in- Two- Binary -Search -Trees
replace `1305- All- Elements- in- Two- Binary -Search -Trees` to `1305- All Elements in Two Binary Search Trees`

2024-07-11 07:51 UTC, Ajay-Dhangar commented on dsa-solutions/lc-solutions/1300-1399/1310 XOR-Queries-Of-A-Subarray.md
> +sidebar_label: 1310 XOR-Queries-Of-A-Subarray
replace `1310 XOR-Queries-Of-A-Subarray` to `1310 XOR Queries Of A Subarray`

2024-07-11 15:51 UTC, Ajay-Dhangar approved these changes
Done

2024-07-11 16:12 UTC, Ajay-Dhangar approved these changes
Debug the code to correct syntax errors.

2024-07-11 17:09 UTC, merged