added gym website template
CodeHarborHub/codeharborhub.github.io pull request #4017
Opened 2024-07-28 11:43 UTC by Ridhima10

Hello PA
Issue resolved- #3594 

![Screenshot 2024-07-28 170703](https://github.com/user-attachments/assets/7288ba38-957c-498e-998f-84e85fd217a1)

2024-07-28 13:57 UTC, Ajay-Dhangar requested changes
update code based on suggestions

2024-07-28 13:57 UTC, Ajay-Dhangar commented on src/data/userData.tsx
> +      "https://github.com/Ridhima10/Crossfits",
replace `website:
      "https://github.com/Ridhima10/Crossfits",` with `website:
      "https://ridhima10.github.io/Crossfits/",`

2024-07-28 18:44 UTC, Ridhima10 commented
@Ajay-Dhangar  its done. kindly merge it

2024-07-29 02:43 UTC, Ajay-Dhangar approved these changes
Done

2024-07-29 03:00 UTC, merged