Upasthiti
CodeHarborHub/codeharborhub.github.io pull request #4179
Opened 2024-08-02 12:30 UTC by Ridhima10

Hello Pa
issue resolved- #4142

2024-08-02 13:30 UTC, Ridhima10 commented
![Screenshot 2024-08-02 190008](https://github.com/user-attachments/assets/9ada74d9-8f96-48a2-8bc8-2c28d5c8cc6b)

2024-08-02 13:35 UTC, Ajay-Dhangar requested changes
Hello, the URL provided does not seem to be correct, as it only shows the content of your README.md file, not the rendered web or source code. Please check the URL and make sure it points to the correct location. Thank you!

2024-08-02 13:35 UTC, Ajay-Dhangar commented on src/data/userData.tsx
> +      website: "https://ridhima10.github.io/Upasthiti-frontend/",
![image](https://github.com/user-attachments/assets/a9ce6777-3c34-4208-a2a1-c74cdd984c33)

2024-08-03 06:45 UTC, Ridhima10 commented
@Ajay-Dhangar okay sure I'll check and correct it if needed!!

2024-08-18 09:56 UTC, closed without merging