Add a Solution for Merge Sorted Array (LeetCode Problem 88)
CodeHarborHub/codeharborhub.github.io pull request #555
Opened 2024-06-05 09:50 UTC by thevijayshankersharma

## Related Issue

fixes #528 

## Description

As requested, I have added the solution for the "Merge Sorted Array" problem from LeetCode. The solution includes:

id, title, desc, label, and tags
Problem statement
Problem description and links
Examples
Constraints
Solution code for Python, Java, and C++
Approach and explanation
Conclusion

This should provide a comprehensive and clear solution to the problem, following the structure and quality of previous solutions. I hope this meets the requirements.

## Type of PR

- [x] Feature enhancement
- [x] Documentation update

## Screenshots / Videos (if applicable)

## Checklist
- [x] I have performed a self-review of my code.
- [x] I have read and followed the Contribution Guidelines.
- [x] I have tested the changes thoroughly before submitting this pull request.
- [x] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [x] I have commented my code, particularly in hard-to-understand areas.

## Additional Context

i followed instaruction as you said
i hope quality of this code impressed you
thank you

## Resources for Guidance

Here are some resources that may be helpful as you contribute to CodeHarborHub:
- [Code Harbor Hub Community Features](https://www.codeharborhub.live/community/features)
- [Docusaurus Documentation](https://docusaurus.io/docs/create-doc)
- [React.js Documentation](https://legacy.reactjs.org/docs/getting-started.html)
- [Markdown Guide](https://www.markdownguide.org/)
- [MDX Documentation](https://mdxjs.com/docs/)
- [Mermaid Documentation](https://mermaid.js.org/)

**Resources for DSA Features on Our Site:**

- Tabs: [Switch Languages](https://www.codeharborhub.live/community/features#multi-language-support-code-blocks)
- [Line Numbering](https://www.codeharborhub.live/community/features#line-numbering)
- [Math Equations](https://www.codeharborhub.live/community/features#math-equations-with-katex)

2024-06-05 17:34 UTC, Ajay-Dhangar requested changes
Now Check it our basic structure https://www.codeharborhub.live/community/features and how to it us. 

And now update based on requirements

2024-06-05 17:34 UTC, Ajay-Dhangar commented on dsa-solutions/lc-solutions/0000-0099/0088-merge-sorted-array.md
> +The above solution efficiently merges two sorted integer arrays `nums1` and `nums2` into a single array `nums1` in non-decreasing order. It utilizes a two-pointer approach to achieve a time complexit
replace `O(m + n)` to `$O(m + n)$`

2024-06-05 17:48 UTC, Ajay-Dhangar requested changes
Please update the code based on the suggestions. Before submitting a pull request, run the code on your system and conduct a self-review. Then, proceed to send the pull request.

2024-06-05 17:48 UTC, Ajay-Dhangar commented on dsa-solutions/lc-solutions/0000-0099/0088-merge-sorted-array.md
> +topics:
remove `Topics: - Array`

2024-06-05 17:48 UTC, Ajay-Dhangar commented on dsa-solutions/lc-solutions/0000-0099/0088-merge-sorted-array.md
> +### Constraints
**Bad Practice**

```md

- `nums1.length == m + n`
- `nums2.length == n`
- `0 <= m, n <= 200`
- `1 <= m + n <= 200`
- `-10^9 <= nums1[i], nums2[j] <= 10^9`
```

**Good Practice**

```md
- $nums1.length == m + n$
- $nums2.length == n$
- $0 <= m, n <= 200$
- $1 <= m + n <= 200$
- $-10^9 <= nums1[i], nums2[j] <= 10^9$
```

2024-06-05 17:48 UTC, Ajay-Dhangar commented on dsa-solutions/lc-solutions/0000-0099/0088-merge-sorted-array.md
> +```
replace 
````md 
```  
// c++ code here
```
```` 
to 
````md 
``` cpp
// c++ code here
```
````

2024-06-05 17:48 UTC, Ajay-Dhangar commented on dsa-solutions/lc-solutions/0000-0099/0088-merge-sorted-array.md
> +```
and for all based on languages

2024-06-06 01:02 UTC, Ajay-Dhangar commented
@thevijayshankersharma I need to close this pull request because it doesn't adhere to our structure, and there are issues with the code. Please create a new, fresh pull request, ensuring that all code is reviewed and aligns with our standards. You may also perform a self-review before sending the new PR

2024-06-06 01:02 UTC, closed without merging

2024-06-06 01:04 UTC, thevijayshankersharma commented
> @thevijayshankersharma I need to close this pull request because it doesn't adhere to our structure, and there are issues with the code. Please create a new, fresh pull request, ensuring that all code is reviewed and aligns with our standards. You may also perform a self-review before sending the new PR

Could you tell more specifically want I want to change.