minimum number od jumps solution added
CodeHarborHub/codeharborhub.github.io pull request #565
Opened 2024-06-05 13:06 UTC by Yashgabani845

## Related Issue
Fixes : #518 

## Description
Added solution of the problem in full deatils 
more than 350 lines of code

1. code in cpp,java,python
2. brute force approch
3. optimal brute force approch 
4. code for every approch
5. expected approch
6. complexity analysis
7. conclusion

## Type of PR

- [x] Feature enhancement
- [x] Documentation update

## Screenshots / Videos (if applicable)

![Screenshot (422)](https://github.com/CodeHarborHub/codeharborhub.github.io/assets/127788321/7661ee17-e865-4b0a-9358-e1a0458d0716)
![Screenshot (421)](https://github.com/CodeHarborHub/codeharborhub.github.io/assets/127788321/c0bf76b8-1ef1-458e-95ac-31c363be9293) and ![Screenshot (420)](https://github.com/CodeHarborHub/codeharborhub.github.io/assets/127788321/3d812721-c714-4f5e-b5b4-386987a44e6d)
## Checklist
- [ ] I have performed a self-review of my code.
- [ ] I have read and followed the Contribution Guidelines.
- [ ] I have tested the changes thoroughly before submitting this pull request.
- [ ] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [ ] I have commented my code, particularly in hard-to-understand areas.

## Additional Context

thanks for this opprtunity kindly go through file changes and if needed give the changes
i will ahppy to improve and learn

## Resources for Guidance

Here are some resources that may be helpful as you contribute to CodeHarborHub:
- [Code Harbor Hub Community Features](https://www.codeharborhub.live/community/features)
- [Docusaurus Documentation](https://docusaurus.io/docs/create-doc)
- [React.js Documentation](https://legacy.reactjs.org/docs/getting-started.html)
- [Markdown Guide](https://www.markdownguide.org/)
- [MDX Documentation](https://mdxjs.com/docs/)
- [Mermaid Documentation](https://mermaid.js.org/)

**Resources for DSA Features on Our Site:**

- Tabs: [Switch Languages](https://www.codeharborhub.live/community/features#multi-language-support-code-blocks)
- [Line Numbering](https://www.codeharborhub.live/community/features#line-numbering)
- [Math Equations](https://www.codeharborhub.live/community/features#math-equations-with-katex)

2024-06-05 13:07 UTC, Yashgabani845 commented
@Ajay-Dhangar done with all works you assigned me yesterday

2024-06-06 04:18 UTC, Ajay-Dhangar requested changes
You can try to remove comments and explain code may be use mermaid graph (like flowchart), and may be used tip for good practice

2024-06-06 04:18 UTC, Ajay-Dhangar commented on dsa-solutions/gfg-solutions/0022-minimum-number-of-jumps.md
> +id: minimum number of jumps
replace `id: minimum number of jumps` to `id: minimum-number-of-jumps`

2024-06-06 04:18 UTC, Ajay-Dhangar commented on dsa-solutions/gfg-solutions/0022-minimum-number-of-jumps.md
> +// C++ Implementation
remove comment `// C++ Implementation`

2024-06-06 04:18 UTC, Ajay-Dhangar commented on dsa-solutions/gfg-solutions/0022-minimum-number-of-jumps.md
> +// C++ Implementation
remove comment `// C++ Implementation`

2024-06-06 04:18 UTC, Ajay-Dhangar commented on dsa-solutions/gfg-solutions/0022-minimum-number-of-jumps.md
> +# Python Implementation
remove comments

2024-06-06 05:06 UTC, Yashgabani845 commented
@Ajay-Dhangar done
removed all comments of cpp implementaiaon, java,python
and also will use flowcharts and graph for next tim instead of using comments 
thanks for your feedback

2024-06-06 10:59 UTC, Ajay-Dhangar approved these changes
Done

2024-06-06 10:59 UTC, merged