Added solutions for the LC problems from 2880-2882
CodeHarborHub/codeharborhub.github.io pull request #568
Opened 2024-06-05 16:20 UTC by Abhay182005dat

**Greetings !!**

I have succesfully added the solutions for the given LC problems sir . :)
Hence this closes #534 

## Description
The solutions are for these three Data Science problems :
- 2880 - Select Data
- 2881 - Create a new column
- 2882 - Drop Duplicate Rows

## Type of PR
- [👍] Feature enhancement
- [👍] Documentation update

2024-06-05 19:20 UTC, Ajay-Dhangar requested changes
now, update code based on suggestions and very important to complete every docs file because your code is not completed. So, first complete all.

2024-06-05 19:20 UTC, Ajay-Dhangar commented on dsa-solutions/lc-solutions/2500 - 3000/2880 - Select Data
> +id : Select Data
replace `id : Select Data` to `id : 2880-select-data`

2024-06-05 19:20 UTC, Ajay-Dhangar commented on dsa-solutions/lc-solutions/2500 - 3000/2880 - Select Data
> +<Tabs>
complete your code because It is not full code so, now complite it

2024-06-06 12:57 UTC, Abhay182005dat commented
Done Sir :)

2024-06-06 15:44 UTC, Abhay182005dat commented
Greetings Sir !!
 
I have completed updating about the Flex-Properties in thw Web-dev section

Hence this closes #572 

Thank You

2024-06-07 01:21 UTC, Ajay-Dhangar commented on web-dev/html/Flex-Box/Flex-Box Properties
> +
delete

```md
Thank You 
-Created by Abhay :)
```

2024-06-07 01:23 UTC, Ajay-Dhangar reviewed
..

2024-06-07 01:35 UTC, merged