All easy gfg solution added
CodeHarborHub/codeharborhub.github.io pull request #570
Opened 2024-06-05 16:50 UTC by Vipullakum007

## Related Issue

fixed : #386 

## Description

i have added solution for all easy problems
**i have added 10 files for solution of 10 problems**

![Screenshot 2024-06-05 221647](https://github.com/CodeHarborHub/codeharborhub.github.io/assets/127659443/c92f2c54-f6ea-49ff-91fe-092991a08582)

## Type of PR

- [ ] Bug fix
- [x] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

## Screenshots / Videos (if applicable)

![Screenshot (677)](https://github.com/CodeHarborHub/codeharborhub.github.io/assets/127659443/5204ea13-0361-40a4-9c47-e3e45266e064)

![Screenshot (678)](https://github.com/CodeHarborHub/codeharborhub.github.io/assets/127659443/e468ff74-15a8-4b62-a4d9-4c350f7c1dab)

![Screenshot (679)](https://github.com/CodeHarborHub/codeharborhub.github.io/assets/127659443/31787745-7338-4616-ae76-e25df9e52ad0)

![Screenshot (680)](https://github.com/CodeHarborHub/codeharborhub.github.io/assets/127659443/f10ba663-3a48-469d-a560-c88b4cbac594)

![Screenshot (681)](https://github.com/CodeHarborHub/codeharborhub.github.io/assets/127659443/2092c690-6fc0-45cd-af86-4e9b4b254c73)

![Screenshot (682)](https://github.com/CodeHarborHub/codeharborhub.github.io/assets/127659443/ec62a601-46ff-4d85-afcf-4cee7d489152)

![Screenshot (683)](https://github.com/CodeHarborHub/codeharborhub.github.io/assets/127659443/59b90810-c174-46f5-b522-c539b2544fd8)

![Screenshot (684)](https://github.com/CodeHarborHub/codeharborhub.github.io/assets/127659443/f77acd92-7460-4892-8104-e071bf657e00)

![Screenshot (685)](https://github.com/CodeHarborHub/codeharborhub.github.io/assets/127659443/51fbd6ee-2ad0-4c0a-ac51-870846f1c90e)

![Screenshot (686)](https://github.com/CodeHarborHub/codeharborhub.github.io/assets/127659443/cf901f5d-66ec-40ff-98e2-dcb68f8f1f75)

## Checklist
- [x] I have performed a self-review of my code.
- [x] I have read and followed the Contribution Guidelines.
- [x] I have tested the changes thoroughly before submitting this pull request.
- [x] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [x] I have commented my code, particularly in hard-to-understand areas.

## Additional Context

[Include any additional information or context that might be helpful for reviewers.]

## Resources for Guidance

Here are some resources that may be helpful as you contribute to CodeHarborHub:
- [Code Harbor Hub Community Features](https://www.codeharborhub.live/community/features)
- [Docusaurus Documentation](https://docusaurus.io/docs/create-doc)
- [React.js Documentation](https://legacy.reactjs.org/docs/getting-started.html)
- [Markdown Guide](https://www.markdownguide.org/)
- [MDX Documentation](https://mdxjs.com/docs/)
- [Mermaid Documentation](https://mermaid.js.org/)

**Resources for DSA Features on Our Site:**

- Tabs: [Switch Languages](https://www.codeharborhub.live/community/features#multi-language-support-code-blocks)
- [Line Numbering](https://www.codeharborhub.live/community/features#line-numbering)
- [Math Equations](https://www.codeharborhub.live/community/features#math-equations-with-katex)

2024-06-05 16:52 UTC, Vipullakum007 commented
hey @Ajay-Dhangar , please make it` level 3 `because i have added solution for all easy problems of gfg there are 10 problem `i have added 10 solution`

2024-06-05 18:00 UTC, Ajay-Dhangar commented
> hey @Ajay-Dhangar , please make it`level 3`because i have added solution for all easy problems of gfg there are 10 problem `i have added 10 solution`

@Vipullakum007 I prefer quality over quantity. I don't need multiple files or folders . You can work on a single file that I assign, possibly at level 3, but ensure it is done professionally. Please make sure your content is clear, well-structured, and thoroughly explained.

2024-06-05 18:35 UTC, Ajay-Dhangar requested changes
Now update code for all files based on suggestions

2024-06-05 18:35 UTC, Ajay-Dhangar commented on dsa-solutions/gfg-solutions/0023-Find-triplet-with-zero-sum.md
> +- -10^3 ≤ arr[i] ≤ 10^3
replace 

```md
- 1 ≤ N ≤ 10^5  
- -10^3 ≤ arr[i] ≤ 10^3
```

to 

```md
- $1 ≤ N ≤ 10^5$
- $-10^3 ≤ arr[i] ≤ 10^3$
```

2024-06-05 18:35 UTC, Ajay-Dhangar commented on dsa-solutions/gfg-solutions/0024-minimum-indexed-character.md
> +- 1 ≤ |str|,|patt| ≤ 10^5
replace

```md
- 1 ≤ |str|,|patt| ≤ 10^5
- 'a' ≤ str[i], patt[i] ≤ 'z'
```

to

```md
- $1 ≤ |str|,|patt| ≤ 10^5$
- $'a' ≤ str[i], patt[i] ≤ 'z'$
```

2024-06-05 18:35 UTC, Ajay-Dhangar commented on dsa-solutions/gfg-solutions/0024-minimum-indexed-character.md
> +- **Time Complexity:** O(N), where N is the length of the string `str`. We iterate through each character in `patt` and use the `find` or `indexOf` method, which runs in O(N) time.
replace `O(N)` to `$O(N)$` and `O(1)` to `$O(1)$`

2024-06-05 18:35 UTC, Ajay-Dhangar commented on dsa-solutions/gfg-solutions/Easy problems/bfs-of-graph.md
> +**Expected Time Complexity:** O(V + E)
replace `O(V + E)` to `$O(V + E)$` and `O(V)` to `$O(V)$`

2024-06-05 18:35 UTC, Ajay-Dhangar commented on dsa-solutions/gfg-solutions/Easy problems/bfs-of-graph.md
> +**Time Complexity:** O(V + E)
replace

`O(V + E)` $=>$ `$O(V + E)$`
`O(V)` $=>$ `$O(V)$`

2024-06-05 18:35 UTC, Ajay-Dhangar commented on dsa-solutions/gfg-solutions/Easy problems/square-root.md
> +**Time Complexity:** O(log N)
replace `O(log N)` to `$O(log N)$` and `O(1)` to `$O(1)$`

2024-06-05 18:35 UTC, Ajay-Dhangar commented on dsa-solutions/gfg-solutions/Easy problems/square-root.md
> +- 1 ≤ x ≤ 10^7
replace `1 ≤ x ≤ 10^7` to `$1 ≤ x ≤ 10^7$`

2024-06-05 18:35 UTC, Ajay-Dhangar commented on dsa-solutions/gfg-solutions/Easy problems/square-root.md
> +**Expected Time Complexity:** O(log N)
replace` O(log N)` to `$O(log N)$` and `O(1)` to `$O(1)$`

2024-06-05 18:35 UTC, Ajay-Dhangar commented on dsa-solutions/gfg-solutions/Easy problems/reverse-a-linked-list.md
> +- **Space Complexity:** O(1), as we only use a constant amount of extra space for pointers.
replace `O(1)` to `$O(1)$` and `O(N)` to `$O(N)$`

2024-06-05 18:35 UTC, Ajay-Dhangar commented on dsa-solutions/gfg-solutions/Easy problems/reverse-a-linked-list.md
> +1 ≤ N ≤ 10^4
**Bad practice**

```md
### Constraints
1 ≤ N ≤ 10^4
```

**Good practice**

```md
### Constraints

- $1 ≤ N ≤ 10^4$
```

2024-06-05 18:35 UTC, Ajay-Dhangar commented on dsa-solutions/gfg-solutions/Easy problems/reverse-a-linked-list.md
> +**Expected Time Complexity:** O(N)
replace `O(N)` to `$O(N)$`
and `O(1)` to `$O(1)$`

2024-06-06 02:17 UTC, Vipullakum007 commented
> > hey @Ajay-Dhangar , please make it`level 3`because i have added solution for all easy problems of gfg there are 10 problem `i have added 10 solution`
> 
> @Vipullakum007 I prefer quality over quantity. I don't need multiple files or folders . You can work on a single file that I assign, possibly at level 3, but ensure it is done professionally. Please make sure your content is clear, well-structured, and thoroughly explained.

please can you point out what you want so that i can better / i can make professionally
i have ask this question many times please answer me.

2024-06-06 02:27 UTC, Vipullakum007 commented
> > > hey @Ajay-Dhangar , please make it`level 3`because i have added solution for all easy problems of gfg there are 10 problem `i have added 10 solution`
> > 
> > 
> > @Vipullakum007 I prefer quality over quantity. I don't need multiple files or folders . You can work on a single file that I assign, possibly at level 3, but ensure it is done professionally. Please make sure your content is clear, well-structured, and thoroughly explained.
> 
> please can you point out what you want so that i can better / i can make professionally i have ask this question many times please answer me.

hey @Ajay-Dhangar , updated as per your suggestion , you can review it. please answer

2024-06-06 04:21 UTC, Ajay-Dhangar commented
> > > hey @Ajay-Dhangar , please make it`level 3`because i have added solution for all easy problems of gfg there are 10 problem `i have added 10 solution`
> > 
> > 
> > @Vipullakum007 I prefer quality over quantity. I don't need multiple files or folders . You can work on a single file that I assign, possibly at level 3, but ensure it is done professionally. Please make sure your content is clear, well-structured, and thoroughly explained.
> 
> please can you point out what you want so that i can better / i can make professionally i have ask this question many times please answer me.

Yah sure, 
I review your work then may be assign good level if your contents is good and fully based on our structures

2024-06-06 04:29 UTC, Ajay-Dhangar requested changes
update your code based on suggestions and can't be use space for maths expression. And review all files code and resolve issues

2024-06-06 04:29 UTC, Ajay-Dhangar commented on dsa-solutions/gfg-solutions/Easy problems/bfs-of-graph.md
> +- $ 1 ≤ V, E ≤ 10^4 $
replace `- $ 1 ≤ V, E ≤ 10^4 $` to `- $1 ≤ V, E ≤ 10^4$`

2024-06-06 04:29 UTC, Ajay-Dhangar commented on dsa-solutions/gfg-solutions/Easy problems/bfs-of-graph.md
> +**Time Complexity:** $ O(V + E)  $
not using space

and replace `$ O(V + E) $` to `$O(V + E)$`

and also, `$ O(V)$` to `$O(V)$`

2024-06-06 04:29 UTC, Ajay-Dhangar commented on dsa-solutions/gfg-solutions/Easy problems/check-for-balanced-tree.md
> +- $ -10^4 <=$ Node.val $<= 10^4 $
replace `- $ -10^4 <=$ Node.val $<= 10^4 $` to `- $-10^4 <=$ Node.val $<= 10^4$`

2024-06-06 04:29 UTC, Ajay-Dhangar commented on dsa-solutions/gfg-solutions/Easy problems/dfs-of-graph.md
> +- **Time Complexity:** $ O(V + E)  $
same issue

2024-06-06 04:29 UTC, Ajay-Dhangar commented on dsa-solutions/gfg-solutions/Easy problems/implement-two-stacks-in-an-array.md
> +The provided solutions efficiently implement two stacks in a single array using pointers. This approach ensures a time complexity of O(1) for all stack operations and an auxiliary space complexity of
replace `O(1)` to `$O(1)$`

2024-06-06 07:07 UTC, Vipullakum007 commented
hey @Ajay-Dhangar  ,updated as per your suggestion

2024-06-06 07:10 UTC, Ajay-Dhangar approved these changes
Done

2024-06-06 07:12 UTC, merged