added leetcode solution for Candy
CodeHarborHub/codeharborhub.github.io pull request #690
Opened 2024-06-07 07:58 UTC by mahek0620

## Related Issue

Closes #683 

## Description

keetcode problem 135 solution added

## Type of PR

- [ ] Bug fix
- [X] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

## Checklist
- [X] I have performed a self-review of my code.
- [X] I have read and followed the Contribution Guidelines.
- [X] I have tested the changes thoroughly before submitting this pull request.
- [X] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [X] I have commented my code, particularly in hard-to-understand areas.

2024-06-07 11:03 UTC, Ajay-Dhangar requested changes
update your code based on suggestions

2024-06-07 11:03 UTC, Ajay-Dhangar commented on dsa-solutions/lc-solutions/0100-0199/0135-Candy.md
> +
**Bad Practice**

```md
- n == ratings.length
- 1 <= n <= 2 * 10^4
- 0 <= ratings[i] <= 2 * 10^4
```

**Good Practice**

```md
- $n == ratings.length$
- $1 <= n <= 2 * 10^4$
- $0 <= ratings[i] <= 2 * 10^4$
```

2024-06-07 11:03 UTC, Ajay-Dhangar commented on dsa-solutions/lc-solutions/0100-0199/0135-Candy.md
> +- Time Complexity: O(n) where n is the number of children (length of the ratings array).
replace `O(n)` to `$O(n)$`

2024-06-07 11:03 UTC, Ajay-Dhangar commented on dsa-solutions/lc-solutions/0100-0199/0135-Candy.md
> +- Space Complexity: O(n) for storing the candies array.
replace `O(n)` to `$O(n)$`

2024-06-07 11:40 UTC, mahek0620 commented
@Ajay-Dhangar the code has been updated based on the suggestion

2024-06-07 11:57 UTC, Ajay-Dhangar approved these changes
Done

2024-06-08 05:20 UTC, Ajay-Dhangar approved these changes
done and fixed bug

2024-06-08 05:25 UTC, merged

2024-07-20 12:02 UTC, Ajay-Dhangar commented
@mahek0620, to calculate the score for your leaderboard, you'll need to add something to those files and then try it out at the bottom. Below is the code you need to include for your author profile in the documentation:

```md
---

<h2>Authors:</h2>

<div style={{display: 'flex', flexWrap: 'wrap', justifyContent: 'space-between', gap: '10px'}}>
{['github_username'].map(username => (
 <Author key={username} username={username} />
))}
</div>
```

2024-07-21 09:26 UTC, mahek0620 commented
@Ajay-Dhangar Do i need to create new PR because this PR is closed I can't edit any file and also can you mention the files which I need to change