Word ladder and word ladder II
CodeHarborHub/codeharborhub.github.io pull request #697
Opened 2024-06-07 09:00 UTC by mahek0620

## Related Issue

Closes #685 

## Description

Added solution for leetcode problems 126 and 127 

## Type of PR

- [ ] Bug fix
- [ ] Feature enhancement
- [X] Documentation update
- [ ] Other (specify): _______________

## Checklist
- [X] I have performed a self-review of my code.
- [X] I have read and followed the Contribution Guidelines.
- [X] I have tested the changes thoroughly before submitting this pull request.
- [X] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [X] I have commented my code, particularly in hard-to-understand areas.

2024-06-07 15:16 UTC, Ajay-Dhangar requested changes
Now update your code and resolve your docker and deployment issues and for Good practice

2024-06-07 15:16 UTC, Ajay-Dhangar commented on dsa-solutions/lc-solutions/0100-0199/0126-word-ladder-II.md
> +A transformation sequence from word beginWord to word endWord using a dictionary wordList is a sequence of words beginWord -> s1 -> s2 -> ... -> sk such that:
**Bad Practice**

```md
-> s1 -> s2 -> ... -> sk
```

**Good Practice**

```md
$s1 -> s2 -> ... -> sk$
```

2024-06-07 15:16 UTC, Ajay-Dhangar commented on dsa-solutions/lc-solutions/0100-0199/0126-word-ladder-II.md
> +Every si for 1 <= i <= k is in wordList. Note that beginWord does not need to be in wordList.
**Bad Practice**

```md
1 <= i <= k
```

**Good Practice**

```md
$1 <= i <= k$
```

2024-06-07 15:16 UTC, Ajay-Dhangar commented on dsa-solutions/lc-solutions/0100-0199/0126-word-ladder-II.md
> +- 1 <= beginWord.length <= 5
replace `1 <= beginWord.length <= 5` to `$1 <= beginWord.length <= 5$`

2024-06-07 15:16 UTC, Ajay-Dhangar commented on dsa-solutions/lc-solutions/0100-0199/0126-word-ladder-II.md
> +- 1 <= wordList.length <= 500
replace `1 <= wordList.length <= 500` to `$1 <= wordList.length <= 500$`

2024-06-07 15:16 UTC, Ajay-Dhangar commented on dsa-solutions/lc-solutions/0100-0199/0126-word-ladder-II.md
> +- endWord.length == beginWord.length
replace `endWord.length == beginWord.length` to`$endWord.length == beginWord.length$`

2024-06-07 15:16 UTC, Ajay-Dhangar commented on dsa-solutions/lc-solutions/0100-0199/0126-word-ladder-II.md
> +- wordList[i].length == beginWord.length
replace `wordList[i].length == beginWord.length` to `$wordList[i].length == beginWord.length$`

2024-06-07 15:16 UTC, Ajay-Dhangar commented on dsa-solutions/lc-solutions/0100-0199/0127-word-ladder.md
> +Every si for 1 <= i <= k is in wordList. Note that beginWord does not need to be in wordList.
replace `1 <= i <= k` to `$1 <= i <= k$`

2024-06-07 15:16 UTC, Ajay-Dhangar commented on dsa-solutions/lc-solutions/0100-0199/0127-word-ladder.md
> +A transformation sequence from word beginWord to word endWord using a dictionary wordList is a sequence of words beginWord -> s1 -> s2 -> ... -> sk such that:
replace `-> s1 -> s2 -> ... ->` to `$-> s1 -> s2 -> ... ->$`

2024-06-07 15:16 UTC, Ajay-Dhangar commented on dsa-solutions/lc-solutions/0100-0199/0127-word-ladder.md
> +### Constraints
**Bad Practice**

```md
### Constraints

- 1 <= beginWord.length <= 10
- endWord.length == beginWord.length
- 1 <= wordList.length <= 5000
- wordList[i].length == beginWord.length
- beginWord, endWord, and wordList[i] consist of lowercase English letters.
- beginWord != endWord
- All the words in wordList are unique.
```

**Good Practice**

```md
### Constraints

- $1 <= beginWord.length <= 10$
- $endWord.length == beginWord.length$
- $1 <= wordList.length <= 5000$
- $wordList[i].length == beginWord.length$
- beginWord, endWord, and $wordList[i]$ consist of lowercase English letters.
- $beginWord != endWord$
- All the words in wordList are unique.
```

2024-06-07 15:16 UTC, Ajay-Dhangar commented on dsa-solutions/lc-solutions/0100-0199/0135-Candy.md
> +
**Bad Practice**

```md
### Constraints

- n == ratings.length
- 1 <= n <= 2 * 10^4
- 0 <= ratings[i] <= 2 * 10^4
```

**Good Practice**

```md
### Constraints

- $n == ratings.length$
- $1 <= n <= 2 * 10^4$
- $0 <= ratings[i] <= 2 * 10^4$
```

2024-06-08 06:36 UTC, Ajay-Dhangar requested changes
Update the code based on the suggestions, solved errors related to Docker, and handle deployment issues.

2024-06-08 06:36 UTC, Ajay-Dhangar commented on dsa-solutions/lc-solutions/0100-0199/0135-Candy.md
> +- 1 <= n <= 2 * 10^4
replace `1 <= n <= 2 * 10^4` to `$1 <= n <= 2 * 10^4$`

2024-06-08 06:36 UTC, Ajay-Dhangar commented on dsa-solutions/lc-solutions/0100-0199/0135-Candy.md
> +- n == ratings.length
replace `n == ratings.length` to `$n == ratings.length$`

2024-06-08 06:36 UTC, Ajay-Dhangar commented on dsa-solutions/lc-solutions/0100-0199/0135-Candy.md
> +- 0 <= ratings[i] <= 2 * 10^4
replace `0 <= ratings[i] <= 2 * 10^4` to `$0 <= ratings[i] <= 2 * 10^4$`

2024-06-08 07:25 UTC, mahek0620 commented
@Ajay-Dhangar the changes you suggested has been modified

2024-06-08 07:35 UTC, Ajay-Dhangar approved these changes
Done

2024-06-08 07:35 UTC, merged

2024-07-20 12:02 UTC, Ajay-Dhangar commented
@mahek0620, to calculate the score for your leaderboard, you'll need to add something to those files and then try it out at the bottom. Below is the code you need to include for your author profile in the documentation:

```md
---

<h2>Authors:</h2>

<div style={{display: 'flex', flexWrap: 'wrap', justifyContent: 'space-between', gap: '10px'}}>
{['github_username'].map(username => (
 <Author key={username} username={username} />
))}
</div>
```