graph algo added
CodeHarborHub/codeharborhub.github.io pull request #713
Opened 2024-06-07 12:14 UTC by Yashgabani845

## Related Issue

Fixes #674 

## Description

added these 3 algo

1. tarjan
2. prims
3. multistage graph 

## Type of PR

- [x] Feature enhancement
- [x] Documentation update

## Screenshots / Videos (if applicable)
![Screenshot (553)](https://github.com/CodeHarborHub/codeharborhub.github.io/assets/127788321/9890b988-6c83-4c84-8da2-f234833855eb)
![Screenshot (554)](https://github.com/CodeHarborHub/codeharborhub.github.io/assets/127788321/5c76401f-bd81-4af0-97ef-96d45a6849f6)
![Screenshot (555)](https://github.com/CodeHarborHub/codeharborhub.github.io/assets/127788321/ea635c90-ad65-4474-afe8-ab1395d2dd61)
![Screenshot (557)](https://github.com/CodeHarborHub/codeharborhub.github.io/assets/127788321/d0361ace-cedd-48d8-b238-be785269ee0d)
![Screenshot (558)](https://github.com/CodeHarborHub/codeharborhub.github.io/assets/127788321/7e60436b-dea1-4a1f-bf9a-158097253125)
![Screenshot (559)](https://github.com/CodeHarborHub/codeharborhub.github.io/assets/127788321/684792ef-bfd2-42ff-bc9f-c64dc593a897)
![Screenshot (560)](https://github.com/CodeHarborHub/codeharborhub.github.io/assets/127788321/b9d42c15-4908-4655-ba86-33881250f355)
![Screenshot (561)](https://github.com/CodeHarborHub/codeharborhub.github.io/assets/127788321/ae380145-58f1-4d9c-92a5-3ba03d6349f9)

[Attach any relevant screenshots or videos demonstrating the changes]

## Checklist
- [ ] I have performed a self-review of my code.
- [ ] I have read and followed the Contribution Guidelines.
- [ ] I have tested the changes thoroughly before submitting this pull request.
- [ ] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [ ] I have commented my code, particularly in hard-to-understand areas.

## Additional Context

[Include any additional information or context that might be helpful for reviewers.]

## Resources for Guidance

Here are some resources that may be helpful as you contribute to CodeHarborHub:
- [Code Harbor Hub Community Features](https://www.codeharborhub.live/community/features)
- [Docusaurus Documentation](https://docusaurus.io/docs/create-doc)
- [React.js Documentation](https://legacy.reactjs.org/docs/getting-started.html)
- [Markdown Guide](https://www.markdownguide.org/)
- [MDX Documentation](https://mdxjs.com/docs/)
- [Mermaid Documentation](https://mermaid.js.org/)

**Resources for DSA Features on Our Site:**

- Tabs: [Switch Languages](https://www.codeharborhub.live/community/features#multi-language-support-code-blocks)
- [Line Numbering](https://www.codeharborhub.live/community/features#line-numbering)
- [Math Equations](https://www.codeharborhub.live/community/features#math-equations-with-katex)

2024-06-07 12:15 UTC, Yashgabani845 commented
@Ajay-Dhangar 
added 3 graph algorithm with deep explanation and implementation in 4 languages

2024-06-07 16:23 UTC, Ajay-Dhangar requested changes
update code based on suggestions

2024-06-07 16:23 UTC, Ajay-Dhangar commented on dsa/Algorithms/multistage-graph.md
> +The Multistage Graph Algorithm efficiently finds the shortest path in a graph divided into stages. It operates in O(V^2) time complexity, making it suitable for graphs with a structured stage-based l
replace `O(V^2)` to `$O(V^2)$`

2024-06-07 16:23 UTC, Ajay-Dhangar commented on dsa/Algorithms/prims.md
> +Prim's Algorithm is an efficient method for finding the Minimum Spanning Tree of a weighted undirected graph. It operates in O(E log V) time complexity using a priority queue, making it suitable for
replace `O(E log V)` to `$O(E log V)$`

2024-06-08 06:42 UTC, Ajay-Dhangar commented
@Yashgabani845, could you please update it? Otherwise, I may need to close it.

2024-06-08 06:43 UTC, Yashgabani845 commented
@Ajay-Dhangar sorry sir  I am doing it rn

2024-06-08 06:48 UTC, Yashgabani845 reviewed
done sir

2024-06-08 07:38 UTC, Ajay-Dhangar approved these changes
Done

2024-06-08 07:38 UTC, merged