Added All Graph Algorithms
CodeHarborHub/codeharborhub.github.io pull request #717
Opened 2024-06-07 14:14 UTC by MuraliDharan7

## Related Issue
- Closes #627 

## Description
Added the Graph algorithms in Algorithms section.
1.Dijkstra's Algorithm: Finds the shortest path between nodes in a graph with non-negative edge weights.
2. Bellman-Ford Algorithm: Computes shortest paths from a single source node to all other nodes, even with negative weights.
3. Floyd-Warshall Algorithm: Finds shortest paths between all pairs of nodes.
4. Kruskal’s and Prim’s Algorithms: Used for finding the minimum spanning tree in a graph.

## Type of PR

- [X] Documentation update

## Screenshots / Videos (if applicable)
![image](https://github.com/CodeHarborHub/codeharborhub.github.io/assets/130668745/218633ed-74e3-4e78-833a-df5ee88036b4)

![image](https://github.com/CodeHarborHub/codeharborhub.github.io/assets/130668745/3217310b-92a2-49fb-ae4a-ef8c4b039298)

## Checklist
- [X] I have performed a self-review of my code.
- [X] I have read and followed the Contribution Guidelines.
- [X] I have tested the changes thoroughly before submitting this pull request.
- [X] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [X] I have commented my code, particularly in hard-to-understand areas.

2024-06-07 14:34 UTC, MuraliDharan7 commented
@Ajay-Dhangar  Can you guide me why does this error occurs..

2024-06-07 15:48 UTC, Ajay-Dhangar commented
> @Ajay-Dhangar Can you guide me why does this error occurs..

yah sure

2024-06-07 15:58 UTC, Ajay-Dhangar requested changes
update your code based on suggestions and resolve issues / errors

2024-06-07 15:58 UTC, Ajay-Dhangar commented on dsa-solutions/index.md
> +- [Graph Algorithms](../dsa/Algorithms/Graph%20Algorithms): Graph Algorithms are algorithms that operate on graphs to solve problems.
replace `Graph%20Algorithms` to `graph-algorithms`

2024-06-07 17:29 UTC, MuraliDharan7 commented
> update your code based on suggestions and resolve issues / errors

Still It has the error, Even after the changes are done

2024-06-08 06:46 UTC, Ajay-Dhangar commented
@MuraliDharan7  please use the correct link because the path link is incorrect.

2024-06-08 06:48 UTC, Ajay-Dhangar requested changes
update your code based on suggestions

2024-06-08 06:48 UTC, Ajay-Dhangar commented on dsa-solutions/index.md
> +- [Graph Algorithms](../dsa/Algorithms/graph-algorithms): Graph Algorithms are algorithms that operate on graphs to solve problems.
replace `../dsa/Algorithms/graph-algorithms` to `/dsa/Algorithms/graph-algorithms`

2024-06-08 08:46 UTC, MuraliDharan7 commented
Since this is keep on getting errors. Can I request new PR for this issue?

2024-06-08 08:46 UTC, MuraliDharan7 commented
> update your code based on suggestions

Changes are done.
Since this is keep on getting errors. Can I request new PR for this issue?

2024-06-08 09:23 UTC, Ajay-Dhangar requested changes
Now, adjust the code according to this approach. I trust you have resolved the error.

2024-06-08 09:23 UTC, Ajay-Dhangar commented on dsa-solutions/index.md
> +- [Graph Algorithms](/dsa/Algorithms/graph-algorithms): Graph Algorithms are algorithms that operate on graphs to solve problems.
You can replace `/dsa/Algorithms/graph-algorithms` with `#`. I will update it. I believe `/dsa/category/graph-algorithms` is working, so please try that instead. Additionally, ensure you are running the project on your local system, as this is a better way to solve errors.

2024-06-08 11:24 UTC, Ajay-Dhangar commented
@MuraliDharan7 complete your task very soon

2024-06-08 11:35 UTC, MuraliDharan7 commented
> Now, adjust the code according to this approach. I trust you can solve the error.

All have passed. Thank you for your guidance.

2024-06-08 11:38 UTC, Ajay-Dhangar approved these changes
done

2024-06-08 11:39 UTC, merged