Create 0152-Maximum-Product-Subarray.md
CodeHarborHub/codeharborhub.github.io pull request #758
Opened 2024-06-08 08:53 UTC by mahek0620

## Related Issue

Closes #699 

## Description

[Please include a brief description of the changes or features added]

## Type of PR

- [ ] Bug fix
- [ ] Feature enhancement
- [X] Documentation update
- [ ] Other (specify): _______________

## Checklist
- [X] I have performed a self-review of my code.
- [X] I have read and followed the Contribution Guidelines.
- [X] I have tested the changes thoroughly before submitting this pull request.
- [X] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [X] I have commented my code, particularly in hard-to-understand areas.

2024-06-08 15:10 UTC, Ajay-Dhangar requested changes
now update your code based on suggestions

2024-06-08 15:10 UTC, Ajay-Dhangar commented on dsa-solutions/lc-solutions/0100-0199/0152-Maximum-Product-Subarray.md
> +- $The product of any prefix or suffix of nums is guaranteed to fit in a 32-bit integer.$
replace `$The product of any prefix or suffix of nums is guaranteed to fit in a 32-bit integer.$` to `The product of any prefix or suffix of nums is guaranteed to fit in a 32-bit integer.`

2024-06-08 15:10 UTC, Ajay-Dhangar commented on dsa-solutions/lc-solutions/0100-0199/0152-Maximum-Product-Subarray.md
> +
remove

```md

</TabItem>

</Tabs>
```

because you used 2 times

2024-06-09 05:47 UTC, mahek0620 commented
@Ajay-Dhangar The code has been modified

2024-06-09 06:20 UTC, Ajay-Dhangar approved these changes
Done

2024-06-09 06:20 UTC, merged

2024-07-20 12:02 UTC, Ajay-Dhangar commented
@mahek0620, to calculate the score for your leaderboard, you'll need to add something to those files and then try it out at the bottom. Below is the code you need to include for your author profile in the documentation:

```md
---

<h2>Authors:</h2>

<div style={{display: 'flex', flexWrap: 'wrap', justifyContent: 'space-between', gap: '10px'}}>
{['github_username'].map(username => (
 <Author key={username} username={username} />
))}
</div>
```