Added leetcode solutions 18-20
CodeHarborHub/codeharborhub.github.io pull request #762
Opened 2024-06-08 10:39 UTC by Hemav009

## Related Issue

#630 

## Description

Added leet code solutions 18-20

## Type of PR

- [ ] Bug fix
- [x] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

## Screenshots / Videos (if applicable)
![image](https://github.com/CodeHarborHub/codeharborhub.github.io/assets/109607812/a15f240f-d2de-4aeb-98b0-1b1109d12d7b)

[Attach any relevant screenshots or videos demonstrating the changes]

## Checklist
- [x] I have performed a self-review of my code.
- [x] I have read and followed the Contribution Guidelines.
- [x] I have tested the changes thoroughly before submitting this pull request.
- [x] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [x] I have commented my code, particularly in hard-to-understand areas.

## Additional Context

[Include any additional information or context that might be helpful for reviewers.]

## Resources for Guidance

Here are some resources that may be helpful as you contribute to CodeHarborHub:
- [Code Harbor Hub Community Features](https://www.codeharborhub.live/community/features)
- [Docusaurus Documentation](https://docusaurus.io/docs/create-doc)
- [React.js Documentation](https://legacy.reactjs.org/docs/getting-started.html)
- [Markdown Guide](https://www.markdownguide.org/)
- [MDX Documentation](https://mdxjs.com/docs/)
- [Mermaid Documentation](https://mermaid.js.org/)

**Resources for DSA Features on Our Site:**

- Tabs: [Switch Languages](https://www.codeharborhub.live/community/features#multi-language-support-code-blocks)
- [Line Numbering](https://www.codeharborhub.live/community/features#line-numbering)
- [Math Equations](https://www.codeharborhub.live/community/features#math-equations-with-katex)

2024-06-08 13:14 UTC, Hemav009 commented
@Ajay-Dhangar  hey can you please explain what this error is?

2024-06-08 15:19 UTC, Ajay-Dhangar commented
> @Ajay-Dhangar hey can you please explain what this error is?

sure, I will help you for debug to code

2024-06-08 15:26 UTC, Ajay-Dhangar requested changes
update code based on suggestions

2024-06-08 15:26 UTC, Ajay-Dhangar commented on dsa-solutions/lc-solutions/0000-0099/0018- FourSum.md
> +description: Given an array nums of n integers, return an array of all the unique quadruplets [nums[a], nums[b], nums[c], nums[d]]
### Bad practice

```md
description: Given an array nums of n integers, return an array of all the unique quadruplets [nums[a], nums[b], nums[c], nums[d]]
```

### Good practice

```md
description: "Given an array nums of n integers, return an array of all the unique quadruplets [nums[a], nums[b], nums[c], nums[d]]"
```

2024-06-08 15:26 UTC, Ajay-Dhangar commented on dsa-solutions/lc-solutions/0000-0099/0018- FourSum.md
> +
### Basic Practice

```md
### Constraints

- `1 <= nums.length <= 200`
- `-10^9 <= nums[i] <= 10^9`
- `-10^9 <= target <= 10^9`
```

### Good Practice

```md
### Constraints

- $1 <= nums.length <= 200$
- $-10^9 <= nums[i] <= 10^9$
- $-10^9 <= target <= 10^9$
```

2024-06-08 15:26 UTC, Ajay-Dhangar commented on dsa-solutions/lc-solutions/0000-0099/0019-remove-nth-node-from-end-of-list.md
> +description: Given the head of a linked list, remove the nth node from the end of the list and return its head.
replace 

`description: Given the head of a linked list, remove the nth node from the end of the list and return its head.`

to

`description: "Given the head of a linked list, remove the nth node from the end of the list and return its head."`

2024-06-08 15:26 UTC, Ajay-Dhangar commented on dsa-solutions/lc-solutions/0000-0099/0019-remove-nth-node-from-end-of-list.md
> +### Constraints
replace 

```md
### Constraints

- The number of nodes in the list is sz.
- `1 <= sz <= 30`
- `0 <= Node.val <= 100`
- `1 <= n <= sz`
```

TO

```md
### Constraints

- The number of nodes in the list is sz.
- $1 <= sz <= 30$
- $0 <= Node.val <= 100$
- $1 <= n <= sz$
```

2024-06-08 15:26 UTC, Ajay-Dhangar commented on dsa-solutions/lc-solutions/0000-0099/0020-valid-parentheses.md
> +description: Given a string s containing just the characters '(', ')', '{', '}', '[' and ']', determine if the input string is valid.
REPLACE

```md
description: Given a string s containing just the characters '(', ')', '{', '}', '[' and ']', determine if the input string is valid.
```

TO

```md
description: "Given a string s containing just the characters '(', ')', '{', '}', '[' and ']', determine if the input string is valid."
```

2024-06-09 04:26 UTC, Hemav009 commented
@Ajay-Dhangar   Updated

2024-06-09 07:35 UTC, Ajay-Dhangar approved these changes
done

2024-06-09 07:36 UTC, merged