Fixes #705 : Resume Builder WebApp
CodeHarborHub/codeharborhub.github.io pull request #767
Opened 2024-06-08 11:31 UTC by Sambit-Mondal

## Related Issue

Fixes the issue no. #705 

## Description

The Resume Builder WebApp consists of the following features:
- It would make the resume building process a cakewalk!
- Just enter the details like, name, personal details, academic details, work experience, skills, etc and boom, the resume will be ready in just a click!
- Also, the user will be able to update the details dynamically, including adding or removing sections, update personal information, or update new skills that they've learnt.
- The users will also be able to view the live resume, while creating it.
- More interestingly, the users will also be able to download their generated resume as PDF.

## Type of PR

- [ ] Bug fix
- [ ] Feature enhancement
- [ ] Documentation update
- [x] Other (specify): Addition of a new project

## Screenshots / Videos (if applicable)

https://github.com/CodeHarborHub/codeharborhub.github.io/assets/138088550/c141e353-5535-45a4-a81b-b2a3457f6774

## Checklist
- [x] I have performed a self-review of my code.
- [x] I have read and followed the Contribution Guidelines.
- [x] I have tested the changes thoroughly before submitting this pull request.
- [x] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [x] I have commented my code, particularly in hard-to-understand areas.

## Additional Context

[Include any additional information or context that might be helpful for reviewers.]

## Resources for Guidance

Here are some resources that may be helpful as you contribute to CodeHarborHub:
- [Code Harbor Hub Community Features](https://www.codeharborhub.live/community/features)
- [Docusaurus Documentation](https://docusaurus.io/docs/create-doc)
- [React.js Documentation](https://legacy.reactjs.org/docs/getting-started.html)
- [Markdown Guide](https://www.markdownguide.org/)
- [MDX Documentation](https://mdxjs.com/docs/)
- [Mermaid Documentation](https://mermaid.js.org/)

**Resources for DSA Features on Our Site:**

- Tabs: [Switch Languages](https://www.codeharborhub.live/community/features#multi-language-support-code-blocks)
- [Line Numbering](https://www.codeharborhub.live/community/features#line-numbering)
- [Math Equations](https://www.codeharborhub.live/community/features#math-equations-with-katex)

2024-06-08 15:35 UTC, Ajay-Dhangar requested changes
update your code based on suggestions

2024-06-08 15:35 UTC, Ajay-Dhangar commented on src/data/users.tsx
> +    description:
Write your **description** limit only 120 characters

so, re-write

2024-06-08 15:39 UTC, Sambit-Mondal commented
@Ajay-Dhangar Done Sir. Kindly check.

2024-06-09 09:21 UTC, Ajay-Dhangar requested changes
@Sambit-Mondal you can close this PRs because I updated code for showcase projects data so, you need first sync or pull our latest main branch for new code then work on it.

2024-06-09 09:22 UTC, closed without merging