Minimum Cost to Connect Two Groups of Points Solution (Leetcode) Added
CodeHarborHub/codeharborhub.github.io pull request #799
Opened 2024-06-08 20:31 UTC by vivekvardhan2810

## Related Issue

Fixed : #783 

## Description

I had Added the Solution of problem "Minimum Cost to Connect Two Groups of Points"  under Leetcode Solution > 1500 - 1599> 1595 House Robber

## Type of PR

- [ ] Bug fix
- [ ] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

## Screenshots / Videos (if applicable)

[Attach any relevant screenshots or videos demonstrating the changes]

## Checklist
- [x] I have performed a self-review of my code.
- [x] I have read and followed the Contribution Guidelines.
- [x] I have tested the changes thoroughly before submitting this pull request.
- [x] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [x] I have commented my code, particularly in hard-to-understand areas.

## Additional Context

[Include any additional information or context that might be helpful for reviewers.]

## Resources for Guidance

Here are some resources that may be helpful as you contribute to CodeHarborHub:
- [Code Harbor Hub Community Features](https://www.codeharborhub.live/community/features)
- [Docusaurus Documentation](https://docusaurus.io/docs/create-doc)
- [React.js Documentation](https://legacy.reactjs.org/docs/getting-started.html)
- [Markdown Guide](https://www.markdownguide.org/)
- [MDX Documentation](https://mdxjs.com/docs/)
- [Mermaid Documentation](https://mermaid.js.org/)

**Resources for DSA Features on Our Site:**

- Tabs: [Switch Languages](https://www.codeharborhub.live/community/features#multi-language-support-code-blocks)
- [Line Numbering](https://www.codeharborhub.live/community/features#line-numbering)
- [Math Equations](https://www.codeharborhub.live/community/features#math-equations-with-katex)

2024-06-08 20:42 UTC, vivekvardhan2810 commented
Hi @Ajay-Dhangar , i have added solution you can review it.

And tell me the suggestions.

2024-06-09 04:07 UTC, Ajay-Dhangar requested changes
update your code based on suggestions

2024-06-09 04:07 UTC, Ajay-Dhangar commented on dsa-solutions/lc-solutions/1500-1599/1595 - Minimum Cost to Connect Two Groups of Points.md
> +You are given two groups of points where the first group has size1 points, the second group has size2 points, and size1 >= size2.
replace `size1 >= size2` to `$size1 >= size2$`

2024-06-09 04:07 UTC, Ajay-Dhangar commented on dsa-solutions/lc-solutions/1500-1599/1595 - Minimum Cost to Connect Two Groups of Points.md
> +You are given two groups of points where the first group has size1 points, the second group has size2 points, and size1 >= size2.
and also, `size1` to `$size1$` , and `size2` to `$size2$`

2024-06-09 06:41 UTC, vivekvardhan2810 commented
@Ajay-Dhangar resolved, can you check it and give suggestions

2024-06-09 09:38 UTC, Ajay-Dhangar approved these changes
Done

2024-06-09 09:39 UTC, merged

2024-06-09 10:16 UTC, vivekvardhan2810 commented
Thank you @Ajay-Dhangar for the Suggestions and support.