Added solution to Leetcode 36(medium) , 37(hard) problems
CodeHarborHub/codeharborhub.github.io pull request #850
Opened 2024-06-09 11:29 UTC by debangi29

## Related Issue

[Cite any related issue(s) this pull request addresses. If none, simply state "None”]

## Description

[Please include a brief description of the changes or features added]

## Type of PR

- [x] Feature enhancement

## Screenshots / Videos (if applicable)

![image](https://github.com/CodeHarborHub/codeharborhub.github.io/assets/117537653/6e8f826d-2b64-449b-86bd-8bade2d66bd3)

![image](https://github.com/CodeHarborHub/codeharborhub.github.io/assets/117537653/e700f159-dea6-40d3-a028-e418d66e345e)

[Attach any relevant screenshots or videos demonstrating the changes]

## Checklist
- [x] I have performed a self-review of my code.
- [x] I have read and followed the Contribution Guidelines.
- [x] I have tested the changes thoroughly before submitting this pull request.
- [x] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [x] I have commented my code, particularly in hard-to-understand areas.

## Additional Context

[Include any additional information or context that might be helpful for reviewers.]

## Resources for Guidance

Here are some resources that may be helpful as you contribute to CodeHarborHub:
- [Code Harbor Hub Community Features](https://www.codeharborhub.live/community/features)
- [Docusaurus Documentation](https://docusaurus.io/docs/create-doc)
- [React.js Documentation](https://legacy.reactjs.org/docs/getting-started.html)
- [Markdown Guide](https://www.markdownguide.org/)
- [MDX Documentation](https://mdxjs.com/docs/)
- [Mermaid Documentation](https://mermaid.js.org/)

**Resources for DSA Features on Our Site:**

- Tabs: [Switch Languages](https://www.codeharborhub.live/community/features#multi-language-support-code-blocks)
- [Line Numbering](https://www.codeharborhub.live/community/features#line-numbering)
- [Math Equations](https://www.codeharborhub.live/community/features#math-equations-with-katex)

2024-06-09 12:30 UTC, debangi29 commented
Hello @Ajay-Dhangar 
I wanted to ask that, pull requests solving one leetcode problem has level 2
This PR solve one easy and one hard problem together
Doesn't it deserve a level 3?
Please check it once...
Thanks a lot :)

2024-06-10 03:13 UTC, Ajay-Dhangar requested changes
now update your code based on suggestions

2024-06-10 03:13 UTC, Ajay-Dhangar commented on dsa-solutions/lc-solutions/0000-0099/0036-Valid-Sudoku.md
> +Determine if a 9 x 9 Sudoku board is valid. Only the filled cells need to be validated according to the following rules:
replace `9 x 9` to `$9 \times 9$`

2024-06-10 03:13 UTC, Ajay-Dhangar commented on dsa-solutions/lc-solutions/0000-0099/0036-Valid-Sudoku.md
> +- Each of the nine 3 x 3 sub-boxes of the grid must contain the digits 1-9 without repetition.
replace `3 x 3` to `$3 \times 3$`

2024-06-10 03:13 UTC, Ajay-Dhangar commented on dsa-solutions/lc-solutions/0000-0099/0036-Valid-Sudoku.md
> +**Input**: board =
### Bad practice

```md
**Input**: board = 
<br>
[["5","3",".",".","7",".",".",".","."]<br>
,["6",".",".","1","9","5",".",".","."]<br>
,[".","9","8",".",".",".",".","6","."]<br>
,["8",".",".",".","6",".",".",".","3"]<br>
,["4",".",".","8",".","3",".",".","1"]<br>
,["7",".",".",".","2",".",".",".","6"]<br>
,[".","6",".",".",".",".","2","8","."]<br>
,[".",".",".","4","1","9",".",".","5"]<br>
,[".",".",".",".","8",".",".","7","9"]]<br>
```

### Good Practice

````md
```
Input: board = 
[["5","3",".",".","7",".",".",".","."]
,["6",".",".","1","9","5",".",".","."]
,[".","9","8",".",".",".",".","6","."]
,["8",".",".",".","6",".",".",".","3"]
,["4",".",".","8",".","3",".",".","1"]
,["7",".",".",".","2",".",".",".","6"]
,[".","6",".",".",".",".","2","8","."]
,[".",".",".","4","1","9",".",".","5"]
,[".",".",".",".","8",".",".","7","9"]]
```
````

2024-06-10 03:13 UTC, Ajay-Dhangar commented on dsa-solutions/lc-solutions/0000-0099/0036-Valid-Sudoku.md
> +- **Input:** board =
and also, change it

2024-06-10 03:13 UTC, Ajay-Dhangar commented on dsa-solutions/lc-solutions/0000-0099/0037-Sudoku-Solver.md
> +<br>
also, change for good practice

2024-06-10 04:27 UTC, debangi29 commented
I have done the changes

Thanks :)

2024-06-10 06:49 UTC, debangi29 commented
Should I do any more changes?
@Ajay-Dhangar

2024-06-10 11:15 UTC, Ajay-Dhangar requested changes
everything is fine but you remove `<br>` tag and solve error

2024-06-10 11:15 UTC, Ajay-Dhangar commented on dsa-solutions/lc-solutions/0000-0099/0036-Valid-Sudoku.md
> +<br>
remove `<br>` tag

2024-06-10 15:30 UTC, Ajay-Dhangar commented on dsa-solutions/lc-solutions/0000-0099/0036-Valid-Sudoku.md
> +<br>
@debangi29 complete your task

2024-06-10 15:40 UTC, debangi29 commented
I have done it @Ajay-Dhangar

2024-06-10 16:35 UTC, Ajay-Dhangar approved these changes
Done

2024-06-10 16:35 UTC, merged