Solution of Leetcode Problem: 98
CodeHarborHub/codeharborhub.github.io pull request #886
Opened 2024-06-09 17:19 UTC by Anshika14528

## Related Issue

closes: #872

## Description

Added solution to leetcode problem 98 (Validate Binary Search Tree)

## Type of PR

- [ ] Bug fix
- [x] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

## Checklist
- [x] I have performed a self-review of my code.
- [x] I have read and followed the Contribution Guidelines.
- [x] I have tested the changes thoroughly before submitting this pull request.
- [x] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [x] I have commented my code, particularly in hard-to-understand areas.

## Resources for Guidance

Here are some resources that may be helpful as you contribute to CodeHarborHub:
- [Code Harbor Hub Community Features](https://www.codeharborhub.live/community/features)
- [Docusaurus Documentation](https://docusaurus.io/docs/create-doc)
- [React.js Documentation](https://legacy.reactjs.org/docs/getting-started.html)
- [Markdown Guide](https://www.markdownguide.org/)
- [MDX Documentation](https://mdxjs.com/docs/)
- [Mermaid Documentation](https://mermaid.js.org/)

**Resources for DSA Features on Our Site:**

- Tabs: [Switch Languages](https://www.codeharborhub.live/community/features#multi-language-support-code-blocks)
- [Line Numbering](https://www.codeharborhub.live/community/features#line-numbering)
- [Math Equations](https://www.codeharborhub.live/community/features#math-equations-with-katex)

2024-06-09 18:06 UTC, Ajay-Dhangar requested changes
update your code based on suggestions

2024-06-09 18:06 UTC, Ajay-Dhangar commented on dsa-solutions/lc-solutions/0000-0099/0098-validate-binary-search-tree.md
> +- -2^(31) <= Node.val <= 2^(31) - 1.
replace `- -2^(31) <= Node.val <= 2^(31) - 1.` to `- $-2^(31) <= Node.val <= 2^(31) - 1$`.

2024-06-09 18:12 UTC, Anshika14528 commented
Done
please review it now @Ajay-Dhangar sir

2024-06-10 03:01 UTC, Anshika14528 commented
@Ajay-Dhangar sir , i have corrected the changes requested please review it now

2024-06-10 05:40 UTC, Ajay-Dhangar requested changes
update based on suggestions

2024-06-10 05:40 UTC, Ajay-Dhangar commented on dsa-solutions/lc-solutions/0000-0099/0098-validate-binary-search-tree.md
> +id: validate binary search tree
replace `validate binary search tree` to `validate-binary-search-tree`

2024-06-10 05:59 UTC, Anshika14528 commented
@Ajay-Dhangar sir, is it ok now i have made the chnages

2024-06-10 07:35 UTC, Ajay-Dhangar approved these changes
Done

2024-06-10 07:36 UTC, merged

2024-06-10 07:37 UTC, Anshika14528 commented
@Ajay-Dhangar sir , why is it duplicate ?

2024-06-10 07:48 UTC, Anshika14528 commented
My all three issues solution(issue no. #872 , #883) was there in this pull request "Added leetcode problem:226 #913"