Sort colors
CodeHarborHub/codeharborhub.github.io pull request #899
Opened 2024-06-09 21:34 UTC by debangi29

## Related Issue
#858 
[Cite any related issue(s) this pull request addresses. If none, simply state "None”]

## Description
Added Solution to Leetcode solution 75, sort-colors
[Please include a brief description of the changes or features added]

## Type of PR

- [x] Feature enhancement

## Screenshots / Videos (if applicable)
![image](https://github.com/CodeHarborHub/codeharborhub.github.io/assets/117537653/a5c5fc29-a67f-427f-b111-7608374af616)

[Attach any relevant screenshots or videos demonstrating the changes]

## Checklist
- [x] I have performed a self-review of my code.
- [x] I have read and followed the Contribution Guidelines.
- [x] I have tested the changes thoroughly before submitting this pull request.
- [x] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [x] I have commented my code, particularly in hard-to-understand areas.

## Additional Context

[Include any additional information or context that might be helpful for reviewers.]

## Resources for Guidance

Here are some resources that may be helpful as you contribute to CodeHarborHub:
- [Code Harbor Hub Community Features](https://www.codeharborhub.live/community/features)
- [Docusaurus Documentation](https://docusaurus.io/docs/create-doc)
- [React.js Documentation](https://legacy.reactjs.org/docs/getting-started.html)
- [Markdown Guide](https://www.markdownguide.org/)
- [MDX Documentation](https://mdxjs.com/docs/)
- [Mermaid Documentation](https://mermaid.js.org/)

**Resources for DSA Features on Our Site:**

- Tabs: [Switch Languages](https://www.codeharborhub.live/community/features#multi-language-support-code-blocks)
- [Line Numbering](https://www.codeharborhub.live/community/features#line-numbering)
- [Math Equations](https://www.codeharborhub.live/community/features#math-equations-with-katex)

2024-06-10 05:59 UTC, Ajay-Dhangar requested changes
update code based on suggestions

2024-06-10 05:59 UTC, Ajay-Dhangar commented on dsa-solutions/lc-solutions/0000-0099/0075-sort-colors.md
> +- n == nums.length
### Bad practice

```md
- n == nums.length
- 1 <= n <= 300
- nums[i] is either 0, 1, or 2
```

### Good Practice

```md
- $n = \text{nums.length}$
- $1 \leq n \leq 300$
- $\text{nums}[i] \in \{0, 1, 2\}$
```

2024-06-10 15:30 UTC, Ajay-Dhangar commented on dsa-solutions/lc-solutions/0000-0099/0075-sort-colors.md
> +- n == nums.length
@debangi29 Complete your task

2024-06-10 17:08 UTC, debangi29 commented
![image](https://github.com/CodeHarborHub/codeharborhub.github.io/assets/117537653/4082b2c0-040f-4bfe-9f9d-1b01bf05bbf1)


I have made the above changes already... Do i need to make any more changes? @Ajay-Dhangar

2024-06-10 17:31 UTC, Ajay-Dhangar requested changes
update code only one error

2024-06-10 17:31 UTC, Ajay-Dhangar commented on dsa-solutions/lc-solutions/0000-0099/0075-sort-colors.md
> +- First, we will run a loop that will continue until mid <= high.
replace `mid <= high` to

```md
`mid <= high`
```

because `<` is introduce tags lisl (html/mdx, and also, jsx) so, not useing directly

2024-06-11 01:17 UTC, Ajay-Dhangar approved these changes
Done

2024-06-11 01:19 UTC, merged