Added Binary Search Topic
CodeHarborHub/codeharborhub.github.io pull request #909
Opened 2024-06-10 03:10 UTC by SadafKausar2025

## Related Issue #859

[Cite any related issue(s) this pull request addresses. If none, simply state "None”]

## Description

[Please include a brief description of the changes or features added]

## Type of PR

- [x] Documentation update

![Screenshot (1968)](https://github.com/CodeHarborHub/codeharborhub.github.io/assets/137484958/dfe254c8-7b07-4050-963f-4d047fcede2a)

https://github.com/CodeHarborHub/codeharborhub.github.io/assets/137484958/88db0c7e-1de1-4da5-8f7a-5cb82004812a

[Attach any relevant screenshots or videos demonstrating the changes]

## Checklist
- [x] I have performed a self-review of my code.
- [x] I have read and followed the Contribution Guidelines.
- [x] I have tested the changes thoroughly before submitting this pull request.
- [x] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [x] I have commented my code, particularly in hard-to-understand areas.

## Additional Context

[Include any additional information or context that might be helpful for reviewers.]

## Resources for Guidance

Here are some resources that may be helpful as you contribute to CodeHarborHub:
- [Code Harbor Hub Community Features](https://www.codeharborhub.live/community/features)
- [Docusaurus Documentation](https://docusaurus.io/docs/create-doc)
- [React.js Documentation](https://legacy.reactjs.org/docs/getting-started.html)
- [Markdown Guide](https://www.markdownguide.org/)
- [MDX Documentation](https://mdxjs.com/docs/)
- [Mermaid Documentation](https://mermaid.js.org/)

**Resources for DSA Features on Our Site:**

- Tabs: [Switch Languages](https://www.codeharborhub.live/community/features#multi-language-support-code-blocks)
- [Line Numbering](https://www.codeharborhub.live/community/features#line-numbering)
- [Math Equations](https://www.codeharborhub.live/community/features#math-equations-with-katex)

2024-06-10 03:10 UTC, SadafKausar2025 commented
hello @Ajay-Dhangar 
can you please review this PR?

2024-06-10 03:21 UTC, SadafKausar2025 commented
Hello @Ajay-Dhangar 
Is this PR all Ok and set?

2024-06-10 03:34 UTC, Ajay-Dhangar requested changes
Now update your code based on suggestions

2024-06-10 03:34 UTC, Ajay-Dhangar commented on docs/dsa/binary_search/binary_search.md
> +Prevent Overflow: When calculating the middle index, use mid = low + (high - low) / 2 instead of mid = (low + high) / 2 to prevent potential overflow.
replace `mid = low + (high - low) / 2` to `$\text{mid} = \text{low} + \frac{\text{high} - \text{low}}{2}$`

2024-06-10 03:34 UTC, Ajay-Dhangar commented on docs/dsa/binary_search/binary_search.md
> +Prevent Overflow: When calculating the middle index, use mid = low + (high - low) / 2 instead of mid = (low + high) / 2 to prevent potential overflow.
and also, `mid = (low + high) / 2` to `$\text{mid} = \frac{\text{low} + \text{high}}{2}$`

2024-06-10 03:34 UTC, Ajay-Dhangar commented on docs/dsa/binary_search/recursive_binary_search.md
> +The time complexity of iterative binary search is
```md
𝑂
(
log
⁡
𝑛
)
O(logn), where
𝑛
```

write in good format

2024-06-10 03:34 UTC, Ajay-Dhangar commented on docs/dsa/binary_search/recursive_binary_search.md
> +The time complexity of iterative binary search is
like `$O(logn)$`

2024-06-10 03:34 UTC, Ajay-Dhangar commented on dsa-solutions/lc-solutions/0000-0099/0017-letter-combinations-of-a-phone-number.md
> +id: Letter Combinations of a Phone Number
Please not edit this file replace it's code to previous code because it's already good format

2024-06-10 03:37 UTC, SadafKausar2025 commented
Ok

2024-06-10 04:12 UTC, SadafKausar2025 commented
hello @Ajay-Dhangar 
can you see this I have corrected the code

2024-06-10 06:33 UTC, Ajay-Dhangar approved these changes
Done. I added some code, but next time, please focus on our structure for best practices.

2024-06-10 06:37 UTC, merged

2024-06-10 07:13 UTC, SadafKausar2025 commented
hello @Ajay-Dhangar 
you have merged but not given level

2024-06-10 07:16 UTC, SadafKausar2025 commented
> Done. I added some code, but next time, please focus on our structure for best practices.

sure, I will
I understood when I see you updated code

2024-06-10 07:16 UTC, SadafKausar2025 commented
@Ajay-Dhangar please give level also

2024-06-16 13:29 UTC, Ajay-Dhangar commented
@sanjay-kv thanks,