added some solution between 3000-3010
CodeHarborHub/codeharborhub.github.io pull request #928
Opened 2024-06-10 09:31 UTC by agarwalhimanshugaya

## Related Issue

Fix: #835 

## Description
I add some of the solution between 3000-3010 which is solved by mine 
## Type of PR

- [ ] Bug fix
- [x] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

## Screenshots / Videos (if applicable)

[Attach any relevant screenshots or videos demonstrating the changes]

## Checklist
- [x] I have performed a self-review of my code.
- [x] I have read and followed the Contribution Guidelines.
- [x] I have tested the changes thoroughly before submitting this pull request.
- [x] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [x] I have commented my code, particularly in hard-to-understand areas.

## Additional Context

[Include any additional information or context that might be helpful for reviewers.]

## Resources for Guidance

Here are some resources that may be helpful as you contribute to CodeHarborHub:
- [Code Harbor Hub Community Features](https://www.codeharborhub.live/community/features)
- [Docusaurus Documentation](https://docusaurus.io/docs/create-doc)
- [React.js Documentation](https://legacy.reactjs.org/docs/getting-started.html)
- [Markdown Guide](https://www.markdownguide.org/)
- [MDX Documentation](https://mdxjs.com/docs/)
- [Mermaid Documentation](https://mermaid.js.org/)

**Resources for DSA Features on Our Site:**

- Tabs: [Switch Languages](https://www.codeharborhub.live/community/features#multi-language-support-code-blocks)
- [Line Numbering](https://www.codeharborhub.live/community/features#line-numbering)
- [Math Equations](https://www.codeharborhub.live/community/features#math-equations-with-katex)

2024-06-10 10:39 UTC, Ajay-Dhangar requested changes
Update all files code base on one files suggestion and can't delete `dsa-solutions/lc-solutions/_category_.json` this file and you need write good format for all files based on suggestions

2024-06-10 10:39 UTC, Ajay-Dhangar commented on dsa-solutions/lc-solutions/3000-3099/3000-Maximum area of diagonal rectangle.md
> +- **Explanation:** $For index = 0, length = 9 and width = 3. Diagonal length = sqrt(9 * 9 + 3 * 3) = sqrt(90) ≈ 9.487.
replace

```md
$For index = 0, length = 9 and width = 3. Diagonal length = sqrt(9 * 9 + 3 * 3) = sqrt(90) ≈ 9.487.
For index = 1, length = 8 and width = 6. Diagonal length = sqrt(8 * 8 + 6 * 6) = sqrt(100) = 10.
So, the rectangle at index 1 has a greater diagonal length therefore we return area = 8 * 6 = 48..$
```

to 

```md
For index = $0$, $\text{length} = 9$ and width = $3$. $\text{Diagonal length} = sqrt(9 \times 9 + 3 \times 3) = sqrt(90) ≈ 9.487$.
For $\text{index} = 1$, $length = 8$ and $\text{width} = 6$. $\text{Diagonal length} = sqrt(8 \times 8 + 6 \times 6) = sqrt(100) = 10$.
So, the rectangle at index 1 has a greater diagonal length therefore we return $area = 8 \times 6 = 48..$
```

2024-06-10 10:39 UTC, Ajay-Dhangar commented on dsa-solutions/lc-solutions/3000-3099/3000-Maximum area of diagonal rectangle.md
> +- $1 <= dimensions.length <= 100$
replace `$1 <= dimensions.length <= 100$` to `$1 \leq  dimensions.length \leq 100$`

2024-06-10 10:39 UTC, Ajay-Dhangar commented on dsa-solutions/lc-solutions/3000-3099/3000-Maximum area of diagonal rectangle.md
> +At last we can say that we can calculate maximum area of diagonal rectangle using timecomplexity of o(n) and spacecomplexity of o(1) using a simple for loop and some variable
replace `o(n)` to `$O(n)$`

2024-06-10 10:48 UTC, agarwalhimanshugaya commented on dsa-solutions/lc-solutions/3000-3099/3000-Maximum area of diagonal rectangle.md
> +- **Explanation:** $For index = 0, length = 9 and width = 3. Diagonal length = sqrt(9 * 9 + 3 * 3) = sqrt(90) ≈ 9.487.
how can i add again category_.json file

2024-06-10 10:55 UTC, agarwalhimanshugaya commented
i apply all your given suggestions

2024-06-10 19:08 UTC, agarwalhimanshugaya commented
i remove all the error mention by you

2024-06-11 06:30 UTC, Ajay-Dhangar requested changes
update your code only one error

2024-06-11 06:30 UTC, Ajay-Dhangar commented on dsa-solutions/lc-solutions/3000-3099/3006-find beautiful indices in the given array.md
> +Basically the problem statement suggest that we need to find the index of string a matching in string s and then check if there is any index j which is matching with b in s and abs(i - j) <= k.
reploace `abs(i - j) <= k` to 

```md
`abs(i - j) <= k`
```

2024-06-11 06:51 UTC, Ajay-Dhangar approved these changes
Done

2024-06-11 07:09 UTC, Ajay-Dhangar requested changes
Update code based on suggestions

2024-06-11 07:09 UTC, Ajay-Dhangar commented on dsa-solutions/lc-solutions/3000-3099/3005-count elements with maximum frequency.md
> +id: Count Elements With Maximum Frequency
replace `id: Count Elements With Maximum Frequency` to `id: count-elements-with-maximum-frequency`

2024-06-11 07:09 UTC, Ajay-Dhangar commented on dsa-solutions/lc-solutions/3000-3099/3010-divide an array into subarrays with minimum cost 1.md
> +id: Divide an Array Into Subarrays With Minimum Cost I
replace `id: Divide an Array Into Subarrays With Minimum Cost I` to `id: divide-an-array-into-subarrays-with-minimum-cost-I`

2024-06-11 07:09 UTC, Ajay-Dhangar commented on dsa-solutions/lc-solutions/3000-3099/3006-find beautiful indices in the given array.md
> +If `v1[i] > v2[j]&& abs( i- j) > k` then keep moving pointer j till v1[i] > v2[j]
replace `v1[i] > v2[j]` to 

```md
`v1[i] > v2[j]`
```

2024-06-11 08:27 UTC, agarwalhimanshugaya commented
mai push krrtha tha to nhi horha tha to muje merge krna pda origin k sath

2024-06-11 08:33 UTC, Ajay-Dhangar commented
> mai push krrtha tha to nhi horha tha to muje merge krna pda origin k sath

okay

2024-06-11 08:34 UTC, Ajay-Dhangar approved these changes
Done

2024-06-11 08:53 UTC, Ajay-Dhangar approved these changes
...

2024-06-11 08:58 UTC, merged