Adding more sections to TypeScript
CodeHarborHub/codeharborhub.github.io pull request #946
Opened 2024-06-10 11:41 UTC by priyavratamohan

## Related Issue

Closes #219 

## Description

Adding a Simple Datatypes, Special Datatypes, Control Flow, Functions, Classes and Inheritance, Interfaces, Advanced Types and 
Generics Sections to TypeScript Docs

## Type of PR

- [ ] Bug fix
- [X] Feature enhancement
- [X] Documentation update
- [ ] Other (specify): _______________

## Screenshots / Videos (if applicable)

![image](https://github.com/CodeHarborHub/codeharborhub.github.io/assets/91372958/68a590cb-bbfa-4eec-826d-af140bda7d0f)
Uploaded a screenshot of the Sidebar, do tell if you need a screenshot of every page

## Checklist
- [X] I have performed a self-review of my code.
- [X] I have read and followed the Contribution Guidelines.
- [X] I have tested the changes thoroughly before submitting this pull request.
- [X] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [X] I have commented my code, particularly in hard-to-understand areas.

Thank you for being patient with the waiting time, and do tell if you need any changes done!

If everything is correct, please merge this PR under the Label of GSSoC '24 and add label 'level 1'/'level 2'/'level 3' according to your discretion.
Thank you!

2024-06-10 16:30 UTC, Ajay-Dhangar requested changes
Now update your all files code replace to <code>```tsx title="typescript"</code> and apply best practices

2024-06-10 16:30 UTC, Ajay-Dhangar commented on docs/typescript/advanced-types-ts.md
> +```<js title='typescript'>
replace

````md
```<js title='typescript'>
````

to

````md
```tsx title="typescript"
````

2024-06-10 16:30 UTC, Ajay-Dhangar commented on docs/typescript/advanced-types-ts.md
> +```<js title='typescript'>
and also, replace to all for best practice

2024-06-10 16:30 UTC, Ajay-Dhangar commented on docs/typescript/classes-ts.md
> +```<js title='typescript'>
same issue so, use like 

````md
```tsx title="typescript"
````

2024-06-10 16:30 UTC, Ajay-Dhangar commented on docs/typescript/classes-ts.md
> +```<js title='typescript'>
replace to <code>```tsx title="typescript"</code>

2024-06-10 16:30 UTC, Ajay-Dhangar commented on docs/typescript/classes-ts.md
> +```<js title='typescript'>
replace to <code>```tsx title="typescript"</code>

2024-06-10 16:30 UTC, Ajay-Dhangar commented on docs/typescript/classes-ts.md
> +```<js title='typescript'>
replace to <code>```tsx title="typescript"</code>

2024-06-10 16:30 UTC, Ajay-Dhangar commented on docs/typescript/classes-ts.md
> +```<js title='typescript'>
replace to <code>```tsx title="typescript"</code>

2024-06-10 16:30 UTC, Ajay-Dhangar commented on docs/typescript/classes-ts.md
> +```<js title='typescript'>
replace to <code>```tsx title="typescript"</code>

2024-06-10 16:30 UTC, Ajay-Dhangar commented on docs/typescript/classes-ts.md
> +```<js title='typescript'>
replace to <code>```tsx title="typescript"</code>

2024-06-10 16:30 UTC, Ajay-Dhangar commented on docs/typescript/control-flow-ts.md
> +```<js title='typescript'>
replace to <code>```tsx title="typescript"</code>

2024-06-11 01:20 UTC, Ajay-Dhangar commented on docs/typescript/control-flow-ts.md
> +```<js title='typescript'>
@priyavratamohan update your code

2024-06-11 07:07 UTC, priyavratamohan commented
@Ajay-Dhangar I've committed the proposed changes. Please do check and let me know if they're correct and consistent with what you wanted.

2024-06-11 09:04 UTC, Ajay-Dhangar approved these changes
Done

2024-06-11 09:08 UTC, merged