[Leetcode]: Valid Parentheses #366
CodeHarborHub/codeharborhub.github.io pull request #954
Opened 2024-06-10 15:32 UTC by nisargaa20

## Related Issue

[Cite any related issue(s) this pull request addresses. If none, simply state "None”]

## Description

[Please include a brief description of the changes or features added]

added leetcode solution 20.Valid Parentheses
Fixed: #366

## Type of PR

- [ ] Bug fix
- [ ] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

## Checklist
- [ ] I have performed a self-review of my code.
- [ ] I have read and followed the Contribution Guidelines.
- [ ] I have tested the changes thoroughly before submitting this pull request.
- [ ] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [ ] I have commented my code, particularly in hard-to-understand areas.

## Additional Context

[Include any additional information or context that might be helpful for reviewers.]

## Resources for Guidance

Here are some resources that may be helpful as you contribute to CodeHarborHub:
- [Code Harbor Hub Community Features](https://www.codeharborhub.live/community/features)
- [Docusaurus Documentation](https://docusaurus.io/docs/create-doc)
- [React.js Documentation](https://legacy.reactjs.org/docs/getting-started.html)
- [Markdown Guide](https://www.markdownguide.org/)
- [MDX Documentation](https://mdxjs.com/docs/)
- [Mermaid Documentation](https://mermaid.js.org/)

**Resources for DSA Features on Our Site:**

- Tabs: [Switch Languages](https://www.codeharborhub.live/community/features#multi-language-support-code-blocks)
- [Line Numbering](https://www.codeharborhub.live/community/features#line-numbering)
- [Math Equations](https://www.codeharborhub.live/community/features#math-equations-with-katex)

2024-06-10 17:25 UTC, Ajay-Dhangar requested changes
update your code only change one line

2024-06-10 17:25 UTC, Ajay-Dhangar commented on dsa-solutions/lc-solutions/0000-0099/0020-valid.parentheses.md
> +- $s consists of parentheses only '()[]{}'.$
replace `- $s consists of parentheses only '()[]{}'.$` to `- s consists of parentheses only '()[]{}'.`

2024-06-11 02:29 UTC, nisargaa20 commented
@Ajay-Dhangar changed and javascript solution too

2024-06-11 06:35 UTC, Ajay-Dhangar approved these changes
Done

2024-06-11 06:41 UTC, merged