Added LinkedList Topic in DSA
CodeHarborHub/codeharborhub.github.io pull request #961
Opened 2024-06-10 16:46 UTC by SadafKausar2025

## Related Issue #950

[Cite any related issue(s) this pull request addresses. If none, simply state "None”]

## Description

[Please include a brief description of the changes or features added]

## Type of PR

- [x] Documentation update

## Screenshots / Videos (if applicable)

https://github.com/CodeHarborHub/codeharborhub.github.io/assets/137484958/564d8a2d-b060-4ec3-82ce-376d5a96bb78

![Screenshot 2024-06-10 221248](https://github.com/CodeHarborHub/codeharborhub.github.io/assets/137484958/79823947-3ca4-4f44-b117-364bac7d1c99)

[Attach any relevant screenshots or videos demonstrating the changes]

## Checklist
- [x] I have performed a self-review of my code.
- [x] I have read and followed the Contribution Guidelines.
- [x] I have tested the changes thoroughly before submitting this pull request.
- [x] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [x] I have commented my code, particularly in hard-to-understand areas.

## Additional Context

[Include any additional information or context that might be helpful for reviewers.]

## Resources for Guidance

Here are some resources that may be helpful as you contribute to CodeHarborHub:
- [Code Harbor Hub Community Features](https://www.codeharborhub.live/community/features)
- [Docusaurus Documentation](https://docusaurus.io/docs/create-doc)
- [React.js Documentation](https://legacy.reactjs.org/docs/getting-started.html)
- [Markdown Guide](https://www.markdownguide.org/)
- [MDX Documentation](https://mdxjs.com/docs/)
- [Mermaid Documentation](https://mermaid.js.org/)

**Resources for DSA Features on Our Site:**

- Tabs: [Switch Languages](https://www.codeharborhub.live/community/features#multi-language-support-code-blocks)
- [Line Numbering](https://www.codeharborhub.live/community/features#line-numbering)
- [Math Equations](https://www.codeharborhub.live/community/features#math-equations-with-katex)

2024-06-10 17:01 UTC, Ajay-Dhangar requested changes
now update code based on suggestions

2024-06-10 23:34 UTC, SadafKausar2025 commented on docs/dsa/linkedlist/LinkedList.md
> +## Table of Contents
ok

2024-06-10 23:45 UTC, SadafKausar2025 commented
hello @Ajay-Dhangar 
done with the changes
can you please review this PR?

2024-06-11 01:21 UTC, Ajay-Dhangar approved these changes
Done

2024-06-11 01:21 UTC, merged